// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file plato/dailygame.proto (package plato, syntax proto3)
/* eslint-disable */

import type {
  GenFile,
  GenMessage,
  GenService,
} from "@bufbuild/protobuf/codegenv2";
import {
  fileDesc,
  messageDesc,
  serviceDesc,
} from "@bufbuild/protobuf/codegenv2";
import type {
  BaseRequest,
  BaseResponse,
  DailyGameIdRequestSchema,
  ModeIdRequestSchema,
} from "./generic_pb";
import { file_plato_generic } from "./generic_pb";
import type {
  AttemptDetailAnswer,
  DailyGameAnswerStats,
  DetailDailyGame,
  Mode,
  PublicDailyGame,
} from "./object_pb";
import { file_plato_object } from "./object_pb";
import { file_validate_validate } from "../validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file plato/dailygame.proto.
 */
export const file_plato_dailygame: GenFile =
  /*@__PURE__*/
  fileDesc(
    "ChVwbGF0by9kYWlseWdhbWUucHJvdG8SBXBsYXRvImwKFU1vZGVEYWlseUdhbWVSZXNwb25zZRIhCgRiYXNlGAEgASgLMhMucGxhdG8uQmFzZVJlc3BvbnNlEhkKBG1vZGUYAiABKAsyCy5wbGF0by5Nb2RlEhUKDWRhaWx5X2dhbWVfaWQYAyABKAQibwoXUHVibGljRGFpbHlHYW1lUmVzcG9uc2USIQoEYmFzZRgBIAEoCzITLnBsYXRvLkJhc2VSZXNwb25zZRIxChFwdWJsaWNfZGFpbHlfZ2FtZRgCIAEoCzIWLnBsYXRvLlB1YmxpY0RhaWx5R2FtZSJvChdEZXRhaWxEYWlseUdhbWVSZXNwb25zZRIhCgRiYXNlGAEgASgLMhMucGxhdG8uQmFzZVJlc3BvbnNlEjEKEWRldGFpbF9kYWlseV9nYW1lGAIgASgLMhYucGxhdG8uRGV0YWlsRGFpbHlHYW1lInUKFEF0dGVtcHRBbnN3ZXJSZXF1ZXN0EioKBGJhc2UYASABKAsyEi5wbGF0by5CYXNlUmVxdWVzdEII+kIFigECEAESHgoNZGFpbHlfZ2FtZV9pZBgCIAEoBEIH+kIEMgIgABIRCglhbnN3ZXJfaWQYBCABKAQixwEKFUF0dGVtcHRBbnN3ZXJSZXNwb25zZRIhCgRiYXNlGAEgASgLMhMucGxhdG8uQmFzZVJlc3BvbnNlEhIKCmlzX2NvcnJlY3QYAiABKAgSOQoVYXR0ZW1wdF9kZXRhaWxfYW5zd2VyGAMgASgLMhoucGxhdG8uQXR0ZW1wdERldGFpbEFuc3dlchI8ChdkYWlseV9nYW1lX2Fuc3dlcl9zdGF0cxgEIAEoCzIbLnBsYXRvLkRhaWx5R2FtZUFuc3dlclN0YXRzMtgCChVQbGF0b0RhaWx5R2FtZVNlcnZpY2USVQoWR2V0RGV0YWlsRGFpbHlHYW1lQnlJZBIZLnBsYXRvLkRhaWx5R2FtZUlkUmVxdWVzdBoeLnBsYXRvLkRldGFpbERhaWx5R2FtZVJlc3BvbnNlIgASTAoUR2V0TW9kZURhaWx5R2FtZUJ5SWQSFC5wbGF0by5Nb2RlSWRSZXF1ZXN0GhwucGxhdG8uTW9kZURhaWx5R2FtZVJlc3BvbnNlIgASTAoSR2V0UHVibGljRGFpbHlHYW1lEhQucGxhdG8uTW9kZUlkUmVxdWVzdBoeLnBsYXRvLlB1YmxpY0RhaWx5R2FtZVJlc3BvbnNlIgASTAoNQXR0ZW1wdEFuc3dlchIbLnBsYXRvLkF0dGVtcHRBbnN3ZXJSZXF1ZXN0GhwucGxhdG8uQXR0ZW1wdEFuc3dlclJlc3BvbnNlIgBCEVoPcGxhdG8vYXBpL3Byb3RvYgZwcm90bzM",
    [file_plato_generic, file_plato_object, file_validate_validate],
  );

/**
 * @generated from message plato.ModeDailyGameResponse
 */
export type ModeDailyGameResponse = Message<"plato.ModeDailyGameResponse"> & {
  /**
   * @generated from field: plato.BaseResponse base = 1;
   */
  base?: BaseResponse;

  /**
   * @generated from field: plato.Mode mode = 2;
   */
  mode?: Mode;

  /**
   * @generated from field: uint64 daily_game_id = 3;
   */
  dailyGameId: bigint;
};

/**
 * Describes the message plato.ModeDailyGameResponse.
 * Use `create(ModeDailyGameResponseSchema)` to create a new message.
 */
export const ModeDailyGameResponseSchema: GenMessage<ModeDailyGameResponse> =
  /*@__PURE__*/
  messageDesc(file_plato_dailygame, 0);

/**
 * @generated from message plato.PublicDailyGameResponse
 */
export type PublicDailyGameResponse =
  Message<"plato.PublicDailyGameResponse"> & {
    /**
     * @generated from field: plato.BaseResponse base = 1;
     */
    base?: BaseResponse;

    /**
     * @generated from field: plato.PublicDailyGame public_daily_game = 2;
     */
    publicDailyGame?: PublicDailyGame;
  };

/**
 * Describes the message plato.PublicDailyGameResponse.
 * Use `create(PublicDailyGameResponseSchema)` to create a new message.
 */
export const PublicDailyGameResponseSchema: GenMessage<PublicDailyGameResponse> =
  /*@__PURE__*/
  messageDesc(file_plato_dailygame, 1);

/**
 * @generated from message plato.DetailDailyGameResponse
 */
export type DetailDailyGameResponse =
  Message<"plato.DetailDailyGameResponse"> & {
    /**
     * @generated from field: plato.BaseResponse base = 1;
     */
    base?: BaseResponse;

    /**
     * @generated from field: plato.DetailDailyGame detail_daily_game = 2;
     */
    detailDailyGame?: DetailDailyGame;
  };

/**
 * Describes the message plato.DetailDailyGameResponse.
 * Use `create(DetailDailyGameResponseSchema)` to create a new message.
 */
export const DetailDailyGameResponseSchema: GenMessage<DetailDailyGameResponse> =
  /*@__PURE__*/
  messageDesc(file_plato_dailygame, 2);

/**
 * @generated from message plato.AttemptAnswerRequest
 */
export type AttemptAnswerRequest = Message<"plato.AttemptAnswerRequest"> & {
  /**
   * @generated from field: plato.BaseRequest base = 1;
   */
  base?: BaseRequest;

  /**
   * @generated from field: uint64 daily_game_id = 2;
   */
  dailyGameId: bigint;

  /**
   * @generated from field: uint64 answer_id = 4;
   */
  answerId: bigint;
};

/**
 * Describes the message plato.AttemptAnswerRequest.
 * Use `create(AttemptAnswerRequestSchema)` to create a new message.
 */
export const AttemptAnswerRequestSchema: GenMessage<AttemptAnswerRequest> =
  /*@__PURE__*/
  messageDesc(file_plato_dailygame, 3);

/**
 * @generated from message plato.AttemptAnswerResponse
 */
export type AttemptAnswerResponse = Message<"plato.AttemptAnswerResponse"> & {
  /**
   * @generated from field: plato.BaseResponse base = 1;
   */
  base?: BaseResponse;

  /**
   * @generated from field: bool is_correct = 2;
   */
  isCorrect: boolean;

  /**
   * @generated from field: plato.AttemptDetailAnswer attempt_detail_answer = 3;
   */
  attemptDetailAnswer?: AttemptDetailAnswer;

  /**
   * @generated from field: plato.DailyGameAnswerStats daily_game_answer_stats = 4;
   */
  dailyGameAnswerStats?: DailyGameAnswerStats;
};

/**
 * Describes the message plato.AttemptAnswerResponse.
 * Use `create(AttemptAnswerResponseSchema)` to create a new message.
 */
export const AttemptAnswerResponseSchema: GenMessage<AttemptAnswerResponse> =
  /*@__PURE__*/
  messageDesc(file_plato_dailygame, 4);

/**
 * @generated from service plato.PlatoDailyGameService
 */
export const PlatoDailyGameService: GenService<{
  /**
   * @generated from rpc plato.PlatoDailyGameService.GetDetailDailyGameById
   */
  getDetailDailyGameById: {
    methodKind: "unary";
    input: typeof DailyGameIdRequestSchema;
    output: typeof DetailDailyGameResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoDailyGameService.GetModeDailyGameById
   */
  getModeDailyGameById: {
    methodKind: "unary";
    input: typeof ModeIdRequestSchema;
    output: typeof ModeDailyGameResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoDailyGameService.GetPublicDailyGame
   */
  getPublicDailyGame: {
    methodKind: "unary";
    input: typeof ModeIdRequestSchema;
    output: typeof PublicDailyGameResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoDailyGameService.AttemptAnswer
   */
  attemptAnswer: {
    methodKind: "unary";
    input: typeof AttemptAnswerRequestSchema;
    output: typeof AttemptAnswerResponseSchema;
  };
}> = /*@__PURE__*/ serviceDesc(file_plato_dailygame, 0);
