// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file plato/generic.proto (package plato, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_validate_validate } from "../validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file plato/generic.proto.
 */
export const file_plato_generic: GenFile =
  /*@__PURE__*/
  fileDesc(
    "ChNwbGF0by9nZW5lcmljLnByb3RvEgVwbGF0byJxCgtCYXNlUmVxdWVzdBIdCgpyZXF1ZXN0X2lkGAEgASgJQgn6QgZyBBABGGQSIQoOcmVxdWVzdF9vcmlnaW4YAiABKAlCCfpCBnIEEAEYZBIUCgd1c2VyX2lkGAMgASgESACIAQFCCgoIX3VzZXJfaWQiKgoMQmFzZVJlc3BvbnNlEgwKBGNvZGUYASABKAkSDAoEZGVzYxgCIAEoCSI8Cg5HZW5lcmljUmVxdWVzdBIqCgRiYXNlGAEgASgLMhIucGxhdG8uQmFzZVJlcXVlc3RCCPpCBYoBAhABIj4KD0dlbmVyaWNSZXNwb25zZRIrCgRiYXNlGAEgASgLMhMucGxhdG8uQmFzZVJlc3BvbnNlQgj6QgWKAQIQASKdAQoPUGFnaW5hdGVSZXF1ZXN0EioKBGJhc2UYASABKAsyEi5wbGF0by5CYXNlUmVxdWVzdEII+kIFigECEAESEgoFbGltaXQYAiABKANIAIgBARITCgZvZmZzZXQYAyABKANIAYgBARIUCgdrZXl3b3JkGAQgASgJSAKIAQFCCAoGX2xpbWl0QgkKB19vZmZzZXRCCgoIX2tleXdvcmQiRwoLU2x1Z1JlcXVlc3QSKgoEYmFzZRgBIAEoCzISLnBsYXRvLkJhc2VSZXF1ZXN0Qgj6QgWKAQIQARIMCgRzbHVnGAIgASgJImEKEFRvcGljTW9kZVJlcXVlc3QSKgoEYmFzZRgBIAEoCzISLnBsYXRvLkJhc2VSZXF1ZXN0Qgj6QgWKAQIQARIQCgh0b3BpY19pZBgCIAEoBBIPCgdtb2RlX2lkGAMgASgEIkwKDU1vZGVJZFJlcXVlc3QSKgoEYmFzZRgBIAEoCzISLnBsYXRvLkJhc2VSZXF1ZXN0Qgj6QgWKAQIQARIPCgdtb2RlX2lkGAIgASgEIk4KDlRvcGljSWRSZXF1ZXN0EioKBGJhc2UYASABKAsyEi5wbGF0by5CYXNlUmVxdWVzdEII+kIFigECEAESEAoIdG9waWNfaWQYAiABKAQiVwoSRGFpbHlHYW1lSWRSZXF1ZXN0EioKBGJhc2UYASABKAsyEi5wbGF0by5CYXNlUmVxdWVzdEII+kIFigECEAESFQoNZGFpbHlfZ2FtZV9pZBgCIAEoBCJQCg9BbnN3ZXJJZFJlcXVlc3QSKgoEYmFzZRgBIAEoCzISLnBsYXRvLkJhc2VSZXF1ZXN0Qgj6QgWKAQIQARIRCglhbnN3ZXJfaWQYAiABKAQiYQoXQW5zd2VyQ2F0ZWdvcnlJZFJlcXVlc3QSKgoEYmFzZRgBIAEoCzISLnBsYXRvLkJhc2VSZXF1ZXN0Qgj6QgWKAQIQARIaChJhbnN3ZXJfY2F0ZWdvcnlfaWQYAiABKARCEVoPcGxhdG8vYXBpL3Byb3RvYgZwcm90bzM",
    [file_validate_validate],
  );

/**
 * @generated from message plato.BaseRequest
 */
export type BaseRequest = Message<"plato.BaseRequest"> & {
  /**
   * @generated from field: string request_id = 1;
   */
  requestId: string;

  /**
   * @generated from field: string request_origin = 2;
   */
  requestOrigin: string;

  /**
   * @generated from field: optional uint64 user_id = 3;
   */
  userId?: bigint;
};

/**
 * Describes the message plato.BaseRequest.
 * Use `create(BaseRequestSchema)` to create a new message.
 */
export const BaseRequestSchema: GenMessage<BaseRequest> =
  /*@__PURE__*/
  messageDesc(file_plato_generic, 0);

/**
 * @generated from message plato.BaseResponse
 */
export type BaseResponse = Message<"plato.BaseResponse"> & {
  /**
   * @generated from field: string code = 1;
   */
  code: string;

  /**
   * @generated from field: string desc = 2;
   */
  desc: string;
};

/**
 * Describes the message plato.BaseResponse.
 * Use `create(BaseResponseSchema)` to create a new message.
 */
export const BaseResponseSchema: GenMessage<BaseResponse> =
  /*@__PURE__*/
  messageDesc(file_plato_generic, 1);

/**
 * @generated from message plato.GenericRequest
 */
export type GenericRequest = Message<"plato.GenericRequest"> & {
  /**
   * @generated from field: plato.BaseRequest base = 1;
   */
  base?: BaseRequest;
};

/**
 * Describes the message plato.GenericRequest.
 * Use `create(GenericRequestSchema)` to create a new message.
 */
export const GenericRequestSchema: GenMessage<GenericRequest> =
  /*@__PURE__*/
  messageDesc(file_plato_generic, 2);

/**
 * @generated from message plato.GenericResponse
 */
export type GenericResponse = Message<"plato.GenericResponse"> & {
  /**
   * @generated from field: plato.BaseResponse base = 1;
   */
  base?: BaseResponse;
};

/**
 * Describes the message plato.GenericResponse.
 * Use `create(GenericResponseSchema)` to create a new message.
 */
export const GenericResponseSchema: GenMessage<GenericResponse> =
  /*@__PURE__*/
  messageDesc(file_plato_generic, 3);

/**
 * @generated from message plato.PaginateRequest
 */
export type PaginateRequest = Message<"plato.PaginateRequest"> & {
  /**
   * @generated from field: plato.BaseRequest base = 1;
   */
  base?: BaseRequest;

  /**
   * @generated from field: optional int64 limit = 2;
   */
  limit?: bigint;

  /**
   * @generated from field: optional int64 offset = 3;
   */
  offset?: bigint;

  /**
   * @generated from field: optional string keyword = 4;
   */
  keyword?: string;
};

/**
 * Describes the message plato.PaginateRequest.
 * Use `create(PaginateRequestSchema)` to create a new message.
 */
export const PaginateRequestSchema: GenMessage<PaginateRequest> =
  /*@__PURE__*/
  messageDesc(file_plato_generic, 4);

/**
 * @generated from message plato.SlugRequest
 */
export type SlugRequest = Message<"plato.SlugRequest"> & {
  /**
   * @generated from field: plato.BaseRequest base = 1;
   */
  base?: BaseRequest;

  /**
   * @generated from field: string slug = 2;
   */
  slug: string;
};

/**
 * Describes the message plato.SlugRequest.
 * Use `create(SlugRequestSchema)` to create a new message.
 */
export const SlugRequestSchema: GenMessage<SlugRequest> =
  /*@__PURE__*/
  messageDesc(file_plato_generic, 5);

/**
 * @generated from message plato.TopicModeRequest
 */
export type TopicModeRequest = Message<"plato.TopicModeRequest"> & {
  /**
   * @generated from field: plato.BaseRequest base = 1;
   */
  base?: BaseRequest;

  /**
   * @generated from field: uint64 topic_id = 2;
   */
  topicId: bigint;

  /**
   * @generated from field: uint64 mode_id = 3;
   */
  modeId: bigint;
};

/**
 * Describes the message plato.TopicModeRequest.
 * Use `create(TopicModeRequestSchema)` to create a new message.
 */
export const TopicModeRequestSchema: GenMessage<TopicModeRequest> =
  /*@__PURE__*/
  messageDesc(file_plato_generic, 6);

/**
 * @generated from message plato.ModeIdRequest
 */
export type ModeIdRequest = Message<"plato.ModeIdRequest"> & {
  /**
   * @generated from field: plato.BaseRequest base = 1;
   */
  base?: BaseRequest;

  /**
   * @generated from field: uint64 mode_id = 2;
   */
  modeId: bigint;
};

/**
 * Describes the message plato.ModeIdRequest.
 * Use `create(ModeIdRequestSchema)` to create a new message.
 */
export const ModeIdRequestSchema: GenMessage<ModeIdRequest> =
  /*@__PURE__*/
  messageDesc(file_plato_generic, 7);

/**
 * @generated from message plato.TopicIdRequest
 */
export type TopicIdRequest = Message<"plato.TopicIdRequest"> & {
  /**
   * @generated from field: plato.BaseRequest base = 1;
   */
  base?: BaseRequest;

  /**
   * @generated from field: uint64 topic_id = 2;
   */
  topicId: bigint;
};

/**
 * Describes the message plato.TopicIdRequest.
 * Use `create(TopicIdRequestSchema)` to create a new message.
 */
export const TopicIdRequestSchema: GenMessage<TopicIdRequest> =
  /*@__PURE__*/
  messageDesc(file_plato_generic, 8);

/**
 * @generated from message plato.DailyGameIdRequest
 */
export type DailyGameIdRequest = Message<"plato.DailyGameIdRequest"> & {
  /**
   * @generated from field: plato.BaseRequest base = 1;
   */
  base?: BaseRequest;

  /**
   * @generated from field: uint64 daily_game_id = 2;
   */
  dailyGameId: bigint;
};

/**
 * Describes the message plato.DailyGameIdRequest.
 * Use `create(DailyGameIdRequestSchema)` to create a new message.
 */
export const DailyGameIdRequestSchema: GenMessage<DailyGameIdRequest> =
  /*@__PURE__*/
  messageDesc(file_plato_generic, 9);

/**
 * @generated from message plato.AnswerIdRequest
 */
export type AnswerIdRequest = Message<"plato.AnswerIdRequest"> & {
  /**
   * @generated from field: plato.BaseRequest base = 1;
   */
  base?: BaseRequest;

  /**
   * @generated from field: uint64 answer_id = 2;
   */
  answerId: bigint;
};

/**
 * Describes the message plato.AnswerIdRequest.
 * Use `create(AnswerIdRequestSchema)` to create a new message.
 */
export const AnswerIdRequestSchema: GenMessage<AnswerIdRequest> =
  /*@__PURE__*/
  messageDesc(file_plato_generic, 10);

/**
 * @generated from message plato.AnswerCategoryIdRequest
 */
export type AnswerCategoryIdRequest =
  Message<"plato.AnswerCategoryIdRequest"> & {
    /**
     * @generated from field: plato.BaseRequest base = 1;
     */
    base?: BaseRequest;

    /**
     * @generated from field: uint64 answer_category_id = 2;
     */
    answerCategoryId: bigint;
  };

/**
 * Describes the message plato.AnswerCategoryIdRequest.
 * Use `create(AnswerCategoryIdRequestSchema)` to create a new message.
 */
export const AnswerCategoryIdRequestSchema: GenMessage<AnswerCategoryIdRequest> =
  /*@__PURE__*/
  messageDesc(file_plato_generic, 11);
