// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file plato/mode.proto (package plato, syntax proto3)
/* eslint-disable */

import type {
  GenFile,
  GenMessage,
  GenService,
} from "@bufbuild/protobuf/codegenv2";
import {
  fileDesc,
  messageDesc,
  serviceDesc,
} from "@bufbuild/protobuf/codegenv2";
import type {
  BaseRequest,
  BaseResponse,
  GenericResponseSchema,
  ModeIdRequestSchema,
  TopicIdRequestSchema,
} from "./generic_pb";
import { file_plato_generic } from "./generic_pb";
import type { DailyGameGuessStats, Mode } from "./object_pb";
import { file_plato_object } from "./object_pb";
import { file_validate_validate } from "../validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file plato/mode.proto.
 */
export const file_plato_mode: GenFile =
  /*@__PURE__*/
  fileDesc(
    "ChBwbGF0by9tb2RlLnByb3RvEgVwbGF0byJSChFMaXN0TW9kZXNSZXNwb25zZRIhCgRiYXNlGAEgASgLMhMucGxhdG8uQmFzZVJlc3BvbnNlEhoKBW1vZGVzGAIgAygLMgsucGxhdG8uTW9kZSKnAQoMTW9kZVJlc3BvbnNlEiEKBGJhc2UYASABKAsyEy5wbGF0by5CYXNlUmVzcG9uc2USGQoEbW9kZRgCIAEoCzILLnBsYXRvLk1vZGUSHQoVY3VycmVudF9kYWlseV9nYW1lX2lkGAMgASgEEjoKFmRhaWx5X2dhbWVfZ3Vlc3Nfc3RhdHMYBCABKAsyGi5wbGF0by5EYWlseUdhbWVHdWVzc1N0YXRzIqkBChFJbnNlcnRNb2RlUmVxdWVzdBIqCgRiYXNlGAEgASgLMhIucGxhdG8uQmFzZVJlcXVlc3RCCPpCBYoBAhABEg0KBXRpdGxlGAIgASgJEhMKC2Rlc2NyaXB0aW9uGAMgASgJEhAKCGljb25fdXJsGAQgASgJEhIKCmJhbm5lcl91cmwYBSABKAkSDAoEc2x1ZxgGIAEoCRIQCgh0b3BpY19pZBgHIAEoBCLfAQoRVXBkYXRlTW9kZVJlcXVlc3QSKgoEYmFzZRgBIAEoCzISLnBsYXRvLkJhc2VSZXF1ZXN0Qgj6QgWKAQIQARIKCgJpZBgCIAEoBBISCgV0aXRsZRgDIAEoCUgAiAEBEhgKC2Rlc2NyaXB0aW9uGAQgASgJSAGIAQESFQoIaWNvbl91cmwYBSABKAlIAogBARIXCgpiYW5uZXJfdXJsGAYgASgJSAOIAQFCCAoGX3RpdGxlQg4KDF9kZXNjcmlwdGlvbkILCglfaWNvbl91cmxCDQoLX2Jhbm5lcl91cmwy0wIKEFBsYXRvTW9kZVNlcnZpY2USOgoLR2V0TW9kZUJ5SWQSFC5wbGF0by5Nb2RlSWRSZXF1ZXN0GhMucGxhdG8uTW9kZVJlc3BvbnNlIgASPQoKSW5zZXJ0TW9kZRIYLnBsYXRvLkluc2VydE1vZGVSZXF1ZXN0GhMucGxhdG8uTW9kZVJlc3BvbnNlIgASPQoKVXBkYXRlTW9kZRIYLnBsYXRvLlVwZGF0ZU1vZGVSZXF1ZXN0GhMucGxhdG8uTW9kZVJlc3BvbnNlIgASPAoKRGVsZXRlTW9kZRIULnBsYXRvLk1vZGVJZFJlcXVlc3QaFi5wbGF0by5HZW5lcmljUmVzcG9uc2UiABJHChJMaXN0TW9kZXNCeVRvcGljSWQSFS5wbGF0by5Ub3BpY0lkUmVxdWVzdBoYLnBsYXRvLkxpc3RNb2Rlc1Jlc3BvbnNlIgBCEVoPcGxhdG8vYXBpL3Byb3RvYgZwcm90bzM",
    [file_plato_generic, file_plato_object, file_validate_validate],
  );

/**
 * @generated from message plato.ListModesResponse
 */
export type ListModesResponse = Message<"plato.ListModesResponse"> & {
  /**
   * @generated from field: plato.BaseResponse base = 1;
   */
  base?: BaseResponse;

  /**
   * @generated from field: repeated plato.Mode modes = 2;
   */
  modes: Mode[];
};

/**
 * Describes the message plato.ListModesResponse.
 * Use `create(ListModesResponseSchema)` to create a new message.
 */
export const ListModesResponseSchema: GenMessage<ListModesResponse> =
  /*@__PURE__*/
  messageDesc(file_plato_mode, 0);

/**
 * @generated from message plato.ModeResponse
 */
export type ModeResponse = Message<"plato.ModeResponse"> & {
  /**
   * @generated from field: plato.BaseResponse base = 1;
   */
  base?: BaseResponse;

  /**
   * @generated from field: plato.Mode mode = 2;
   */
  mode?: Mode;

  /**
   * @generated from field: uint64 current_daily_game_id = 3;
   */
  currentDailyGameId: bigint;

  /**
   * @generated from field: plato.DailyGameGuessStats daily_game_guess_stats = 4;
   */
  dailyGameGuessStats?: DailyGameGuessStats;
};

/**
 * Describes the message plato.ModeResponse.
 * Use `create(ModeResponseSchema)` to create a new message.
 */
export const ModeResponseSchema: GenMessage<ModeResponse> =
  /*@__PURE__*/
  messageDesc(file_plato_mode, 1);

/**
 * @generated from message plato.InsertModeRequest
 */
export type InsertModeRequest = Message<"plato.InsertModeRequest"> & {
  /**
   * @generated from field: plato.BaseRequest base = 1;
   */
  base?: BaseRequest;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * @generated from field: string icon_url = 4;
   */
  iconUrl: string;

  /**
   * @generated from field: string banner_url = 5;
   */
  bannerUrl: string;

  /**
   * @generated from field: string slug = 6;
   */
  slug: string;

  /**
   * @generated from field: uint64 topic_id = 7;
   */
  topicId: bigint;
};

/**
 * Describes the message plato.InsertModeRequest.
 * Use `create(InsertModeRequestSchema)` to create a new message.
 */
export const InsertModeRequestSchema: GenMessage<InsertModeRequest> =
  /*@__PURE__*/
  messageDesc(file_plato_mode, 2);

/**
 * @generated from message plato.UpdateModeRequest
 */
export type UpdateModeRequest = Message<"plato.UpdateModeRequest"> & {
  /**
   * @generated from field: plato.BaseRequest base = 1;
   */
  base?: BaseRequest;

  /**
   * @generated from field: uint64 id = 2;
   */
  id: bigint;

  /**
   * @generated from field: optional string title = 3;
   */
  title?: string;

  /**
   * @generated from field: optional string description = 4;
   */
  description?: string;

  /**
   * @generated from field: optional string icon_url = 5;
   */
  iconUrl?: string;

  /**
   * @generated from field: optional string banner_url = 6;
   */
  bannerUrl?: string;
};

/**
 * Describes the message plato.UpdateModeRequest.
 * Use `create(UpdateModeRequestSchema)` to create a new message.
 */
export const UpdateModeRequestSchema: GenMessage<UpdateModeRequest> =
  /*@__PURE__*/
  messageDesc(file_plato_mode, 3);

/**
 * @generated from service plato.PlatoModeService
 */
export const PlatoModeService: GenService<{
  /**
   * @generated from rpc plato.PlatoModeService.GetModeById
   */
  getModeById: {
    methodKind: "unary";
    input: typeof ModeIdRequestSchema;
    output: typeof ModeResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoModeService.InsertMode
   */
  insertMode: {
    methodKind: "unary";
    input: typeof InsertModeRequestSchema;
    output: typeof ModeResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoModeService.UpdateMode
   */
  updateMode: {
    methodKind: "unary";
    input: typeof UpdateModeRequestSchema;
    output: typeof ModeResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoModeService.DeleteMode
   */
  deleteMode: {
    methodKind: "unary";
    input: typeof ModeIdRequestSchema;
    output: typeof GenericResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoModeService.ListModesByTopicId
   */
  listModesByTopicId: {
    methodKind: "unary";
    input: typeof TopicIdRequestSchema;
    output: typeof ListModesResponseSchema;
  };
}> = /*@__PURE__*/ serviceDesc(file_plato_mode, 0);
