// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file core.proto (package core, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file core.proto.
 */
export const file_core: GenFile =
  /*@__PURE__*/
  fileDesc(
    "Cgpjb3JlLnByb3RvEgRjb3JlIs8BCgtCYXNlUmVxdWVzdBISCgpyZXF1ZXN0X2lkGAEgASgJEhYKDnJlcXVlc3Rfb3JpZ2luGAIgASgJEhQKDHJlcXVlc3RfcGF0aBgDIAEoCRISCgppcF9hZGRyZXNzGAQgASgJEhQKB3VzZXJfaWQYBSABKAVIAIgBARIVCgh1c2VybmFtZRgGIAEoCUgBiAEBEhYKCXVzZXJfdHlwZRgHIAEoBUgCiAEBQgoKCF91c2VyX2lkQgsKCV91c2VybmFtZUIMCgpfdXNlcl90eXBlIioKDEJhc2VSZXNwb25zZRIMCgRjb2RlGAEgASgJEgwKBGRlc2MYAiABKAkiMQoOR2VuZXJpY1JlcXVlc3QSHwoEYmFzZRgBIAEoCzIRLmNvcmUuQmFzZVJlcXVlc3QiMwoPR2VuZXJpY1Jlc3BvbnNlEiAKBGJhc2UYASABKAsyEi5jb3JlLkJhc2VSZXNwb25zZUItWitnaXRodWIuY29tL2N5bnhlZXMvY3lueC1jb3JlL3Byb3RvL2dlbjtjb3JlYgZwcm90bzM",
    [file_google_protobuf_timestamp],
  );

/**
 * @generated from message core.BaseRequest
 */
export type BaseRequest = Message<"core.BaseRequest"> & {
  /**
   * @generated from field: string request_id = 1;
   */
  requestId: string;

  /**
   * @generated from field: string request_origin = 2;
   */
  requestOrigin: string;

  /**
   * @generated from field: string request_path = 3;
   */
  requestPath: string;

  /**
   * @generated from field: string ip_address = 4;
   */
  ipAddress: string;

  /**
   * @generated from field: optional int32 user_id = 5;
   */
  userId?: number;

  /**
   * @generated from field: optional string username = 6;
   */
  username?: string;

  /**
   * 0 Guest, 1 Normal
   *
   * @generated from field: optional int32 user_type = 7;
   */
  userType?: number;
};

/**
 * Describes the message core.BaseRequest.
 * Use `create(BaseRequestSchema)` to create a new message.
 */
export const BaseRequestSchema: GenMessage<BaseRequest> =
  /*@__PURE__*/
  messageDesc(file_core, 0);

/**
 * @generated from message core.BaseResponse
 */
export type BaseResponse = Message<"core.BaseResponse"> & {
  /**
   * @generated from field: string code = 1;
   */
  code: string;

  /**
   * @generated from field: string desc = 2;
   */
  desc: string;
};

/**
 * Describes the message core.BaseResponse.
 * Use `create(BaseResponseSchema)` to create a new message.
 */
export const BaseResponseSchema: GenMessage<BaseResponse> =
  /*@__PURE__*/
  messageDesc(file_core, 1);

/**
 * @generated from message core.GenericRequest
 */
export type GenericRequest = Message<"core.GenericRequest"> & {
  /**
   * @generated from field: core.BaseRequest base = 1;
   */
  base?: BaseRequest;
};

/**
 * Describes the message core.GenericRequest.
 * Use `create(GenericRequestSchema)` to create a new message.
 */
export const GenericRequestSchema: GenMessage<GenericRequest> =
  /*@__PURE__*/
  messageDesc(file_core, 2);

/**
 * @generated from message core.GenericResponse
 */
export type GenericResponse = Message<"core.GenericResponse"> & {
  /**
   * @generated from field: core.BaseResponse base = 1;
   */
  base?: BaseResponse;
};

/**
 * Describes the message core.GenericResponse.
 * Use `create(GenericResponseSchema)` to create a new message.
 */
export const GenericResponseSchema: GenMessage<GenericResponse> =
  /*@__PURE__*/
  messageDesc(file_core, 3);
