// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file hermes/user.proto (package user, syntax proto3)
/* eslint-disable */

import type {
  GenFile,
  GenMessage,
  GenService,
} from "@bufbuild/protobuf/codegenv2";
import {
  fileDesc,
  messageDesc,
  serviceDesc,
} from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file hermes/user.proto.
 */
export const file_hermes_user: GenFile =
  /*@__PURE__*/
  fileDesc(
    "ChFoZXJtZXMvdXNlci5wcm90bxIEdXNlciIqCgxCYXNlUmVzcG9uc2USDAoEY29kZRgBIAEoCRIMCgRkZXNjGAIgASgJIigKFENoZWNrVXNlcm5hbWVSZXF1ZXN0EhAKCHVzZXJuYW1lGAEgASgJIkkKFUNoZWNrVXNlcm5hbWVSZXNwb25zZRIgCgRiYXNlGAEgASgLMhIudXNlci5CYXNlUmVzcG9uc2USDgoGZXhpc3RzGAIgASgIIiIKDkdldFVzZXJSZXF1ZXN0EhAKCHVzZXJuYW1lGAEgASgJIlEKD0dldFVzZXJSZXNwb25zZRIgCgRiYXNlGAEgASgLMhIudXNlci5CYXNlUmVzcG9uc2USHAoEdXNlchgCIAEoCzIOLnVzZXIuVXNlckRhdGEiPQoXVmFsaWRhdGVQYXNzd29yZFJlcXVlc3QSEAoIdXNlcm5hbWUYASABKAkSEAoIcGFzc3dvcmQYAiABKAkiWgoYVmFsaWRhdGVQYXNzd29yZFJlc3BvbnNlEiAKBGJhc2UYASABKAsyEi51c2VyLkJhc2VSZXNwb25zZRIcCgR1c2VyGAIgASgLMg4udXNlci5Vc2VyRGF0YSI3ChFDcmVhdGVVc2VyUmVxdWVzdBIQCgh1c2VybmFtZRgBIAEoCRIQCghwYXNzd29yZBgCIAEoCSJUChJDcmVhdGVVc2VyUmVzcG9uc2USIAoEYmFzZRgBIAEoCzISLnVzZXIuQmFzZVJlc3BvbnNlEhwKBHVzZXIYAiABKAsyDi51c2VyLlVzZXJEYXRhIlMKD1BhZ2luYXRlUmVxdWVzdBIMCgRwYWdlGAEgASgFEg0KBWxpbWl0GAIgASgFEg8KB3NvcnRfYnkYAyABKAkSEgoKc29ydF9vcmRlchgEIAEoCSKZAQoVUGFnaW5hdGVVc2Vyc1Jlc3BvbnNlEiAKBGJhc2UYASABKAsyEi51c2VyLkJhc2VSZXNwb25zZRIdCgV1c2VycxgCIAMoCzIOLnVzZXIuVXNlckRhdGESDQoFdG90YWwYAyABKAUSDAoEcGFnZRgEIAEoBRINCgVsaW1pdBgFIAEoBRITCgt0b3RhbF9wYWdlcxgGIAEoBSKaAQoIVXNlckRhdGESCgoCaWQYASABKAUSEAoIdXNlcm5hbWUYAiABKAkSDAoEY29pbhgDIAEoBRIwCgxjcmVhdGVkX2RhdGUYBCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEjAKDHVwZGF0ZWRfZGF0ZRgFIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAy+AIKEUhlcm1lc1VzZXJTZXJ2aWNlEkoKDUNoZWNrVXNlcm5hbWUSGi51c2VyLkNoZWNrVXNlcm5hbWVSZXF1ZXN0GhsudXNlci5DaGVja1VzZXJuYW1lUmVzcG9uc2UiABI4CgdHZXRVc2VyEhQudXNlci5HZXRVc2VyUmVxdWVzdBoVLnVzZXIuR2V0VXNlclJlc3BvbnNlIgASQQoKQ3JlYXRlVXNlchIXLnVzZXIuQ3JlYXRlVXNlclJlcXVlc3QaGC51c2VyLkNyZWF0ZVVzZXJSZXNwb25zZSIAEkUKDVBhZ2luYXRlVXNlcnMSFS51c2VyLlBhZ2luYXRlUmVxdWVzdBobLnVzZXIuUGFnaW5hdGVVc2Vyc1Jlc3BvbnNlIgASUwoQVmFsaWRhdGVQYXNzd29yZBIdLnVzZXIuVmFsaWRhdGVQYXNzd29yZFJlcXVlc3QaHi51c2VyLlZhbGlkYXRlUGFzc3dvcmRSZXNwb25zZSIAQhdaFWhlcm1lcy9hcGkvcHJvdG8vdXNlcmIGcHJvdG8z",
    [file_google_protobuf_timestamp],
  );

/**
 * @generated from message user.BaseResponse
 */
export type BaseResponse = Message<"user.BaseResponse"> & {
  /**
   * @generated from field: string code = 1;
   */
  code: string;

  /**
   * @generated from field: string desc = 2;
   */
  desc: string;
};

/**
 * Describes the message user.BaseResponse.
 * Use `create(BaseResponseSchema)` to create a new message.
 */
export const BaseResponseSchema: GenMessage<BaseResponse> =
  /*@__PURE__*/
  messageDesc(file_hermes_user, 0);

/**
 * Request message for checking username
 *
 * @generated from message user.CheckUsernameRequest
 */
export type CheckUsernameRequest = Message<"user.CheckUsernameRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;
};

/**
 * Describes the message user.CheckUsernameRequest.
 * Use `create(CheckUsernameRequestSchema)` to create a new message.
 */
export const CheckUsernameRequestSchema: GenMessage<CheckUsernameRequest> =
  /*@__PURE__*/
  messageDesc(file_hermes_user, 1);

/**
 * Response message for checking username
 *
 * @generated from message user.CheckUsernameResponse
 */
export type CheckUsernameResponse = Message<"user.CheckUsernameResponse"> & {
  /**
   * @generated from field: user.BaseResponse base = 1;
   */
  base?: BaseResponse;

  /**
   * @generated from field: bool exists = 2;
   */
  exists: boolean;
};

/**
 * Describes the message user.CheckUsernameResponse.
 * Use `create(CheckUsernameResponseSchema)` to create a new message.
 */
export const CheckUsernameResponseSchema: GenMessage<CheckUsernameResponse> =
  /*@__PURE__*/
  messageDesc(file_hermes_user, 2);

/**
 * Request message for getting user
 *
 * @generated from message user.GetUserRequest
 */
export type GetUserRequest = Message<"user.GetUserRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;
};

/**
 * Describes the message user.GetUserRequest.
 * Use `create(GetUserRequestSchema)` to create a new message.
 */
export const GetUserRequestSchema: GenMessage<GetUserRequest> =
  /*@__PURE__*/
  messageDesc(file_hermes_user, 3);

/**
 * Response message for getting user
 *
 * @generated from message user.GetUserResponse
 */
export type GetUserResponse = Message<"user.GetUserResponse"> & {
  /**
   * @generated from field: user.BaseResponse base = 1;
   */
  base?: BaseResponse;

  /**
   * @generated from field: user.UserData user = 2;
   */
  user?: UserData;
};

/**
 * Describes the message user.GetUserResponse.
 * Use `create(GetUserResponseSchema)` to create a new message.
 */
export const GetUserResponseSchema: GenMessage<GetUserResponse> =
  /*@__PURE__*/
  messageDesc(file_hermes_user, 4);

/**
 * Request message for getting user
 *
 * @generated from message user.ValidatePasswordRequest
 */
export type ValidatePasswordRequest =
  Message<"user.ValidatePasswordRequest"> & {
    /**
     * @generated from field: string username = 1;
     */
    username: string;

    /**
     * @generated from field: string password = 2;
     */
    password: string;
  };

/**
 * Describes the message user.ValidatePasswordRequest.
 * Use `create(ValidatePasswordRequestSchema)` to create a new message.
 */
export const ValidatePasswordRequestSchema: GenMessage<ValidatePasswordRequest> =
  /*@__PURE__*/
  messageDesc(file_hermes_user, 5);

/**
 * Response message for getting user
 *
 * @generated from message user.ValidatePasswordResponse
 */
export type ValidatePasswordResponse =
  Message<"user.ValidatePasswordResponse"> & {
    /**
     * @generated from field: user.BaseResponse base = 1;
     */
    base?: BaseResponse;

    /**
     * @generated from field: user.UserData user = 2;
     */
    user?: UserData;
  };

/**
 * Describes the message user.ValidatePasswordResponse.
 * Use `create(ValidatePasswordResponseSchema)` to create a new message.
 */
export const ValidatePasswordResponseSchema: GenMessage<ValidatePasswordResponse> =
  /*@__PURE__*/
  messageDesc(file_hermes_user, 6);

/**
 * Request message for creating user
 *
 * @generated from message user.CreateUserRequest
 */
export type CreateUserRequest = Message<"user.CreateUserRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message user.CreateUserRequest.
 * Use `create(CreateUserRequestSchema)` to create a new message.
 */
export const CreateUserRequestSchema: GenMessage<CreateUserRequest> =
  /*@__PURE__*/
  messageDesc(file_hermes_user, 7);

/**
 * Response message for creating user
 *
 * @generated from message user.CreateUserResponse
 */
export type CreateUserResponse = Message<"user.CreateUserResponse"> & {
  /**
   * @generated from field: user.BaseResponse base = 1;
   */
  base?: BaseResponse;

  /**
   * @generated from field: user.UserData user = 2;
   */
  user?: UserData;
};

/**
 * Describes the message user.CreateUserResponse.
 * Use `create(CreateUserResponseSchema)` to create a new message.
 */
export const CreateUserResponseSchema: GenMessage<CreateUserResponse> =
  /*@__PURE__*/
  messageDesc(file_hermes_user, 8);

/**
 * Request message for paginating users
 *
 * @generated from message user.PaginateRequest
 */
export type PaginateRequest = Message<"user.PaginateRequest"> & {
  /**
   * @generated from field: int32 page = 1;
   */
  page: number;

  /**
   * @generated from field: int32 limit = 2;
   */
  limit: number;

  /**
   * @generated from field: string sort_by = 3;
   */
  sortBy: string;

  /**
   * @generated from field: string sort_order = 4;
   */
  sortOrder: string;
};

/**
 * Describes the message user.PaginateRequest.
 * Use `create(PaginateRequestSchema)` to create a new message.
 */
export const PaginateRequestSchema: GenMessage<PaginateRequest> =
  /*@__PURE__*/
  messageDesc(file_hermes_user, 9);

/**
 * Response message for paginating users
 *
 * @generated from message user.PaginateUsersResponse
 */
export type PaginateUsersResponse = Message<"user.PaginateUsersResponse"> & {
  /**
   * @generated from field: user.BaseResponse base = 1;
   */
  base?: BaseResponse;

  /**
   * @generated from field: repeated user.UserData users = 2;
   */
  users: UserData[];

  /**
   * @generated from field: int32 total = 3;
   */
  total: number;

  /**
   * @generated from field: int32 page = 4;
   */
  page: number;

  /**
   * @generated from field: int32 limit = 5;
   */
  limit: number;

  /**
   * @generated from field: int32 total_pages = 6;
   */
  totalPages: number;
};

/**
 * Describes the message user.PaginateUsersResponse.
 * Use `create(PaginateUsersResponseSchema)` to create a new message.
 */
export const PaginateUsersResponseSchema: GenMessage<PaginateUsersResponse> =
  /*@__PURE__*/
  messageDesc(file_hermes_user, 10);

/**
 * User response message
 *
 * @generated from message user.UserData
 */
export type UserData = Message<"user.UserData"> & {
  /**
   * @generated from field: int32 id = 1;
   */
  id: number;

  /**
   * @generated from field: string username = 2;
   */
  username: string;

  /**
   * @generated from field: int32 coin = 3;
   */
  coin: number;

  /**
   * @generated from field: google.protobuf.Timestamp created_date = 4;
   */
  createdDate?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_date = 5;
   */
  updatedDate?: Timestamp;
};

/**
 * Describes the message user.UserData.
 * Use `create(UserDataSchema)` to create a new message.
 */
export const UserDataSchema: GenMessage<UserData> =
  /*@__PURE__*/
  messageDesc(file_hermes_user, 11);

/**
 * User service definition
 *
 * @generated from service user.HermesUserService
 */
export const HermesUserService: GenService<{
  /**
   * Check if a username exists
   *
   * @generated from rpc user.HermesUserService.CheckUsername
   */
  checkUsername: {
    methodKind: "unary";
    input: typeof CheckUsernameRequestSchema;
    output: typeof CheckUsernameResponseSchema;
  };
  /**
   * Get user by username
   *
   * @generated from rpc user.HermesUserService.GetUser
   */
  getUser: {
    methodKind: "unary";
    input: typeof GetUserRequestSchema;
    output: typeof GetUserResponseSchema;
  };
  /**
   * Create new user
   *
   * @generated from rpc user.HermesUserService.CreateUser
   */
  createUser: {
    methodKind: "unary";
    input: typeof CreateUserRequestSchema;
    output: typeof CreateUserResponseSchema;
  };
  /**
   * Paginate users
   *
   * @generated from rpc user.HermesUserService.PaginateUsers
   */
  paginateUsers: {
    methodKind: "unary";
    input: typeof PaginateRequestSchema;
    output: typeof PaginateUsersResponseSchema;
  };
  /**
   * @generated from rpc user.HermesUserService.ValidatePassword
   */
  validatePassword: {
    methodKind: "unary";
    input: typeof ValidatePasswordRequestSchema;
    output: typeof ValidatePasswordResponseSchema;
  };
}> = /*@__PURE__*/ serviceDesc(file_hermes_user, 0);
