// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file core/core.proto (package plato, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file core/core.proto.
 */
export const file_core_core: GenFile =
  /*@__PURE__*/
  fileDesc(
    "Cg9jb3JlL2NvcmUucHJvdG8SBXBsYXRvIu8BCgtCYXNlUmVxdWVzdBIdCgpyZXF1ZXN0X2lkGAEgASgJQgm6SAZyBBABGGQSIQoOcmVxdWVzdF9vcmlnaW4YAiABKAlCCbpIBnIEEAEYZBIfCgxyZXF1ZXN0X3BhdGgYAyABKAlCCbpIBnIEEAEYZBI3Cgl0aW1lc3RhbXAYBCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wQgi6SAWyAQI4ARIUCgd1c2VyX2lkGAUgASgESACIAQESFQoIdXNlcm5hbWUYBiABKAlIAYgBAUIKCghfdXNlcl9pZEILCglfdXNlcm5hbWUiKgoMQmFzZVJlc3BvbnNlEgwKBGNvZGUYASABKAkSDAoEZGVzYxgCIAEoCSI6Cg5HZW5lcmljUmVxdWVzdBIoCgRiYXNlGAEgASgLMhIucGxhdG8uQmFzZVJlcXVlc3RCBrpIA8gBASI8Cg9HZW5lcmljUmVzcG9uc2USKQoEYmFzZRgBIAEoCzITLnBsYXRvLkJhc2VSZXNwb25zZUIGukgDyAEBQjpaOGdpdGh1Yi5jb20vY3lueGVlcy9qYW51cy1nYXRld2F5L2FwaS9wcm90by9nZW4vY29yZTtjb3JlYgZwcm90bzM",
    [file_google_protobuf_timestamp],
  );

/**
 * @generated from message plato.BaseRequest
 */
export type BaseRequest = Message<"plato.BaseRequest"> & {
  /**
   * string length 1–100
   *
   * @generated from field: string request_id = 1;
   */
  requestId: string;

  /**
   * @generated from field: string request_origin = 2;
   */
  requestOrigin: string;

  /**
   * @generated from field: string request_path = 3;
   */
  requestPath: string;

  /**
   * timestamp must be in the past
   *
   * @generated from field: google.protobuf.Timestamp timestamp = 4;
   */
  timestamp?: Timestamp;

  /**
   * @generated from field: optional uint64 user_id = 5;
   */
  userId?: bigint;

  /**
   * @generated from field: optional string username = 6;
   */
  username?: string;
};

/**
 * Describes the message plato.BaseRequest.
 * Use `create(BaseRequestSchema)` to create a new message.
 */
export const BaseRequestSchema: GenMessage<BaseRequest> =
  /*@__PURE__*/
  messageDesc(file_core_core, 0);

/**
 * @generated from message plato.BaseResponse
 */
export type BaseResponse = Message<"plato.BaseResponse"> & {
  /**
   * @generated from field: string code = 1;
   */
  code: string;

  /**
   * @generated from field: string desc = 2;
   */
  desc: string;
};

/**
 * Describes the message plato.BaseResponse.
 * Use `create(BaseResponseSchema)` to create a new message.
 */
export const BaseResponseSchema: GenMessage<BaseResponse> =
  /*@__PURE__*/
  messageDesc(file_core_core, 1);

/**
 * @generated from message plato.GenericRequest
 */
export type GenericRequest = Message<"plato.GenericRequest"> & {
  /**
   * @generated from field: plato.BaseRequest base = 1;
   */
  base?: BaseRequest;
};

/**
 * Describes the message plato.GenericRequest.
 * Use `create(GenericRequestSchema)` to create a new message.
 */
export const GenericRequestSchema: GenMessage<GenericRequest> =
  /*@__PURE__*/
  messageDesc(file_core_core, 2);

/**
 * @generated from message plato.GenericResponse
 */
export type GenericResponse = Message<"plato.GenericResponse"> & {
  /**
   * @generated from field: plato.BaseResponse base = 1;
   */
  base?: BaseResponse;
};

/**
 * Describes the message plato.GenericResponse.
 * Use `create(GenericResponseSchema)` to create a new message.
 */
export const GenericResponseSchema: GenMessage<GenericResponse> =
  /*@__PURE__*/
  messageDesc(file_core_core, 3);
