// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file hermes/generic.proto (package hermes, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { BaseRequest } from "../core_pb";
import { file_core } from "../core_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file hermes/generic.proto.
 */
export const file_hermes_generic: GenFile =
  /*@__PURE__*/
  fileDesc(
    "ChRoZXJtZXMvZ2VuZXJpYy5wcm90bxIGaGVybWVzIkQKD1VzZXJuYW1lUmVxdWVzdBIfCgRiYXNlGAEgASgLMhEuY29yZS5CYXNlUmVxdWVzdBIQCgh1c2VybmFtZRgCIAEoCSJeChdVc2VybmFtZVBhc3N3b3JkUmVxdWVzdBIfCgRiYXNlGAEgASgLMhEuY29yZS5CYXNlUmVxdWVzdBIQCgh1c2VybmFtZRgCIAEoCRIQCghwYXNzd29yZBgDIAEoCSLcAQoPUGFnaW5hdGVSZXF1ZXN0Eh8KBGJhc2UYASABKAsyES5jb3JlLkJhc2VSZXF1ZXN0EhIKBWxpbWl0GAIgASgFSACIAQESEwoGb2Zmc2V0GAMgASgFSAGIAQESFAoHa2V5d29yZBgEIAEoCUgCiAEBEhQKB3NvcnRfYnkYBSABKAlIA4gBARIXCgpzb3J0X29yZGVyGAYgASgJSASIAQFCCAoGX2xpbWl0QgkKB19vZmZzZXRCCgoIX2tleXdvcmRCCgoIX3NvcnRfYnlCDQoLX3NvcnRfb3JkZXJCEloQaGVybWVzL2FwaS9wcm90b2IGcHJvdG8z",
    [file_core],
  );

/**
 * @generated from message hermes.UsernameRequest
 */
export type UsernameRequest = Message<"hermes.UsernameRequest"> & {
  /**
   * @generated from field: core.BaseRequest base = 1;
   */
  base?: BaseRequest;

  /**
   * @generated from field: string username = 2;
   */
  username: string;
};

/**
 * Describes the message hermes.UsernameRequest.
 * Use `create(UsernameRequestSchema)` to create a new message.
 */
export const UsernameRequestSchema: GenMessage<UsernameRequest> =
  /*@__PURE__*/
  messageDesc(file_hermes_generic, 0);

/**
 * @generated from message hermes.UsernamePasswordRequest
 */
export type UsernamePasswordRequest =
  Message<"hermes.UsernamePasswordRequest"> & {
    /**
     * @generated from field: core.BaseRequest base = 1;
     */
    base?: BaseRequest;

    /**
     * @generated from field: string username = 2;
     */
    username: string;

    /**
     * @generated from field: string password = 3;
     */
    password: string;
  };

/**
 * Describes the message hermes.UsernamePasswordRequest.
 * Use `create(UsernamePasswordRequestSchema)` to create a new message.
 */
export const UsernamePasswordRequestSchema: GenMessage<UsernamePasswordRequest> =
  /*@__PURE__*/
  messageDesc(file_hermes_generic, 1);

/**
 * @generated from message hermes.PaginateRequest
 */
export type PaginateRequest = Message<"hermes.PaginateRequest"> & {
  /**
   * @generated from field: core.BaseRequest base = 1;
   */
  base?: BaseRequest;

  /**
   * @generated from field: optional int32 limit = 2;
   */
  limit?: number;

  /**
   * @generated from field: optional int32 offset = 3;
   */
  offset?: number;

  /**
   * @generated from field: optional string keyword = 4;
   */
  keyword?: string;

  /**
   * @generated from field: optional string sort_by = 5;
   */
  sortBy?: string;

  /**
   * @generated from field: optional string sort_order = 6;
   */
  sortOrder?: string;
};

/**
 * Describes the message hermes.PaginateRequest.
 * Use `create(PaginateRequestSchema)` to create a new message.
 */
export const PaginateRequestSchema: GenMessage<PaginateRequest> =
  /*@__PURE__*/
  messageDesc(file_hermes_generic, 2);
