// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file hermes/object.proto (package hermes, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file hermes/object.proto.
 */
export const file_hermes_object: GenFile =
  /*@__PURE__*/
  fileDesc(
    "ChNoZXJtZXMvb2JqZWN0LnByb3RvEgZoZXJtZXMiwwEKBFVzZXISCgoCaWQYASABKAUSEAoIdXNlcm5hbWUYAiABKAkSDAoEY29pbhgDIAEoBRIRCgl1c2VyX3R5cGUYBCABKAUSGAoQdXNlcl90eXBlX3N0cmluZxgFIAEoCRIwCgxjcmVhdGVkX2RhdGUYCiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEjAKDHVwZGF0ZWRfZGF0ZRgLIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBCEloQaGVybWVzL2FwaS9wcm90b2IGcHJvdG8z",
    [file_google_protobuf_timestamp],
  );

/**
 * @generated from message hermes.User
 */
export type User = Message<"hermes.User"> & {
  /**
   * @generated from field: int32 id = 1;
   */
  id: number;

  /**
   * @generated from field: string username = 2;
   */
  username: string;

  /**
   * @generated from field: int32 coin = 3;
   */
  coin: number;

  /**
   * @generated from field: int32 user_type = 4;
   */
  userType: number;

  /**
   * @generated from field: string user_type_string = 5;
   */
  userTypeString: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_date = 10;
   */
  createdDate?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_date = 11;
   */
  updatedDate?: Timestamp;
};

/**
 * Describes the message hermes.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> =
  /*@__PURE__*/
  messageDesc(file_hermes_object, 0);
