// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file hermes/user.proto (package hermes, syntax proto3)
/* eslint-disable */

import type {
  GenFile,
  GenMessage,
  GenService,
} from "@bufbuild/protobuf/codegenv2";
import {
  fileDesc,
  messageDesc,
  serviceDesc,
} from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { BaseResponse, GenericRequestSchema } from "../core_pb";
import { file_core } from "../core_pb";
import type {
  PaginateRequestSchema,
  UsernamePasswordRequestSchema,
  UsernameRequestSchema,
} from "./generic_pb";
import { file_hermes_generic } from "./generic_pb";
import type { User } from "./object_pb";
import { file_hermes_object } from "./object_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file hermes/user.proto.
 */
export const file_hermes_user: GenFile =
  /*@__PURE__*/
  fileDesc(
    "ChFoZXJtZXMvdXNlci5wcm90bxIGaGVybWVzIkwKDFVzZXJSZXNwb25zZRIgCgRiYXNlGAEgASgLMhIuY29yZS5CYXNlUmVzcG9uc2USGgoEdXNlchgCIAEoCzIMLmhlcm1lcy5Vc2VyIkkKFUNoZWNrVXNlcm5hbWVSZXNwb25zZRIgCgRiYXNlGAEgASgLMhIuY29yZS5CYXNlUmVzcG9uc2USDgoGZXhpc3RzGAIgASgIIlYKFVBhZ2luYXRlVXNlcnNSZXNwb25zZRIgCgRiYXNlGAEgASgLMhIuY29yZS5CYXNlUmVzcG9uc2USGwoFdXNlcnMYAiADKAsyDC5oZXJtZXMuVXNlcjKKBAoRSGVybWVzVXNlclNlcnZpY2USSQoNQ2hlY2tVc2VybmFtZRIXLmhlcm1lcy5Vc2VybmFtZVJlcXVlc3QaHS5oZXJtZXMuQ2hlY2tVc2VybmFtZVJlc3BvbnNlIgASOgoHR2V0VXNlchIXLmhlcm1lcy5Vc2VybmFtZVJlcXVlc3QaFC5oZXJtZXMuVXNlclJlc3BvbnNlIgASRQoKQ3JlYXRlVXNlchIfLmhlcm1lcy5Vc2VybmFtZVBhc3N3b3JkUmVxdWVzdBoULmhlcm1lcy5Vc2VyUmVzcG9uc2UiABJOChNDcmVhdGVVc2VyRnJvbUd1ZXN0Eh8uaGVybWVzLlVzZXJuYW1lUGFzc3dvcmRSZXF1ZXN0GhQuaGVybWVzLlVzZXJSZXNwb25zZSIAEj8KD1Vwc2VydEd1ZXN0VXNlchIULmNvcmUuR2VuZXJpY1JlcXVlc3QaFC5oZXJtZXMuVXNlclJlc3BvbnNlIgASSQoNUGFnaW5hdGVVc2VycxIXLmhlcm1lcy5QYWdpbmF0ZVJlcXVlc3QaHS5oZXJtZXMuUGFnaW5hdGVVc2Vyc1Jlc3BvbnNlIgASSwoQVmFsaWRhdGVQYXNzd29yZBIfLmhlcm1lcy5Vc2VybmFtZVBhc3N3b3JkUmVxdWVzdBoULmhlcm1lcy5Vc2VyUmVzcG9uc2UiAEISWhBoZXJtZXMvYXBpL3Byb3RvYgZwcm90bzM",
    [
      file_google_protobuf_timestamp,
      file_core,
      file_hermes_generic,
      file_hermes_object,
    ],
  );

/**
 * @generated from message hermes.UserResponse
 */
export type UserResponse = Message<"hermes.UserResponse"> & {
  /**
   * @generated from field: core.BaseResponse base = 1;
   */
  base?: BaseResponse;

  /**
   * @generated from field: hermes.User user = 2;
   */
  user?: User;
};

/**
 * Describes the message hermes.UserResponse.
 * Use `create(UserResponseSchema)` to create a new message.
 */
export const UserResponseSchema: GenMessage<UserResponse> =
  /*@__PURE__*/
  messageDesc(file_hermes_user, 0);

/**
 * Response message for checking username
 *
 * @generated from message hermes.CheckUsernameResponse
 */
export type CheckUsernameResponse = Message<"hermes.CheckUsernameResponse"> & {
  /**
   * @generated from field: core.BaseResponse base = 1;
   */
  base?: BaseResponse;

  /**
   * @generated from field: bool exists = 2;
   */
  exists: boolean;
};

/**
 * Describes the message hermes.CheckUsernameResponse.
 * Use `create(CheckUsernameResponseSchema)` to create a new message.
 */
export const CheckUsernameResponseSchema: GenMessage<CheckUsernameResponse> =
  /*@__PURE__*/
  messageDesc(file_hermes_user, 1);

/**
 * Response message for paginating users
 *
 * @generated from message hermes.PaginateUsersResponse
 */
export type PaginateUsersResponse = Message<"hermes.PaginateUsersResponse"> & {
  /**
   * @generated from field: core.BaseResponse base = 1;
   */
  base?: BaseResponse;

  /**
   * @generated from field: repeated hermes.User users = 2;
   */
  users: User[];
};

/**
 * Describes the message hermes.PaginateUsersResponse.
 * Use `create(PaginateUsersResponseSchema)` to create a new message.
 */
export const PaginateUsersResponseSchema: GenMessage<PaginateUsersResponse> =
  /*@__PURE__*/
  messageDesc(file_hermes_user, 2);

/**
 * User service definition
 *
 * @generated from service hermes.HermesUserService
 */
export const HermesUserService: GenService<{
  /**
   * Check if a username exists
   *
   * @generated from rpc hermes.HermesUserService.CheckUsername
   */
  checkUsername: {
    methodKind: "unary";
    input: typeof UsernameRequestSchema;
    output: typeof CheckUsernameResponseSchema;
  };
  /**
   * Get user by username
   *
   * @generated from rpc hermes.HermesUserService.GetUser
   */
  getUser: {
    methodKind: "unary";
    input: typeof UsernameRequestSchema;
    output: typeof UserResponseSchema;
  };
  /**
   * Create new user
   *
   * @generated from rpc hermes.HermesUserService.CreateUser
   */
  createUser: {
    methodKind: "unary";
    input: typeof UsernamePasswordRequestSchema;
    output: typeof UserResponseSchema;
  };
  /**
   * @generated from rpc hermes.HermesUserService.CreateUserFromGuest
   */
  createUserFromGuest: {
    methodKind: "unary";
    input: typeof UsernamePasswordRequestSchema;
    output: typeof UserResponseSchema;
  };
  /**
   * Create new user
   *
   * @generated from rpc hermes.HermesUserService.UpsertGuestUser
   */
  upsertGuestUser: {
    methodKind: "unary";
    input: typeof GenericRequestSchema;
    output: typeof UserResponseSchema;
  };
  /**
   * Paginate users
   *
   * @generated from rpc hermes.HermesUserService.PaginateUsers
   */
  paginateUsers: {
    methodKind: "unary";
    input: typeof PaginateRequestSchema;
    output: typeof PaginateUsersResponseSchema;
  };
  /**
   * @generated from rpc hermes.HermesUserService.ValidatePassword
   */
  validatePassword: {
    methodKind: "unary";
    input: typeof UsernamePasswordRequestSchema;
    output: typeof UserResponseSchema;
  };
}> = /*@__PURE__*/ serviceDesc(file_hermes_user, 0);
