// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file plato/answer.proto (package plato, syntax proto3)
/* eslint-disable */

import type {
  GenFile,
  GenMessage,
  GenService,
} from "@bufbuild/protobuf/codegenv2";
import {
  fileDesc,
  messageDesc,
  serviceDesc,
} from "@bufbuild/protobuf/codegenv2";
import type { AnswerIdRequestSchema, TopicIdRequestSchema } from "./generic_pb";
import { file_plato_generic } from "./generic_pb";
import type { Answer, DetailAnswer } from "./object_pb";
import { file_plato_object } from "./object_pb";

import type {
  BaseRequest,
  BaseResponse,
  GenericResponseSchema,
} from "../core_pb";
import { file_core } from "../core_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file plato/answer.proto.
 */
export const file_plato_answer: GenFile =
  /*@__PURE__*/
  fileDesc(
    "ChJwbGF0by9hbnN3ZXIucHJvdG8SBXBsYXRvInQKFFNlYXJjaEFuc3dlcnNSZXF1ZXN0Eh8KBGJhc2UYASABKAsyES5jb3JlLkJhc2VSZXF1ZXN0EhgKBXF1ZXJ5GAIgASgJQgm6SAZyBBABGGQSEAoIdG9waWNfaWQYAyABKAUSDwoHbW9kZV9pZBgEIAEoBSJXChNMaXN0QW5zd2Vyc1Jlc3BvbnNlEiAKBGJhc2UYASABKAsyEi5jb3JlLkJhc2VSZXNwb25zZRIeCgdhbnN3ZXJzGAIgAygLMg0ucGxhdG8uQW5zd2VyImoKGUxpc3REZXRhaWxBbnN3ZXJzUmVzcG9uc2USIAoEYmFzZRgBIAEoCzISLmNvcmUuQmFzZVJlc3BvbnNlEisKDmRldGFpbF9hbnN3ZXJzGAIgAygLMhMucGxhdG8uRGV0YWlsQW5zd2VyIlEKDkFuc3dlclJlc3BvbnNlEiAKBGJhc2UYASABKAsyEi5jb3JlLkJhc2VSZXNwb25zZRIdCgZhbnN3ZXIYAiABKAsyDS5wbGF0by5BbnN3ZXIiZAoURGV0YWlsQW5zd2VyUmVzcG9uc2USIAoEYmFzZRgBIAEoCzISLmNvcmUuQmFzZVJlc3BvbnNlEioKDWRldGFpbF9hbnN3ZXIYAiABKAsyEy5wbGF0by5EZXRhaWxBbnN3ZXIilwEKE0luc2VydEFuc3dlclJlcXVlc3QSJwoEYmFzZRgBIAEoCzIRLmNvcmUuQmFzZVJlcXVlc3RCBrpIA8gBARIMCgRuYW1lGAIgASgJEhUKCGljb25fdXJsGAMgASgJSACIAQESEwoLYW5zd2VyX3R5cGUYBCABKAkSEAoIdG9waWNfaWQYCiABKAVCCwoJX2ljb25fdXJsIqYBChNVcGRhdGVBbnN3ZXJSZXF1ZXN0EicKBGJhc2UYASABKAsyES5jb3JlLkJhc2VSZXF1ZXN0Qga6SAPIAQESEQoEbmFtZRgCIAEoCUgAiAEBEhUKCGljb25fdXJsGAMgASgJSAGIAQESEwoLYW5zd2VyX3R5cGUYBCABKAkSEQoJYW5zd2VyX2lkGAogASgFQgcKBV9uYW1lQgsKCV9pY29uX3VybDLhBAoSUGxhdG9BbnN3ZXJTZXJ2aWNlEkAKDUdldEFuc3dlckJ5SWQSFi5wbGF0by5BbnN3ZXJJZFJlcXVlc3QaFS5wbGF0by5BbnN3ZXJSZXNwb25zZSIAEkwKE0dldERldGFpbEFuc3dlckJ5SWQSFi5wbGF0by5BbnN3ZXJJZFJlcXVlc3QaGy5wbGF0by5EZXRhaWxBbnN3ZXJSZXNwb25zZSIAEksKFExpc3RBbnN3ZXJzQnlUb3BpY0lkEhUucGxhdG8uVG9waWNJZFJlcXVlc3QaGi5wbGF0by5MaXN0QW5zd2Vyc1Jlc3BvbnNlIgASVwoaTGlzdERldGFpbEFuc3dlcnNCeVRvcGljSWQSFS5wbGF0by5Ub3BpY0lkUmVxdWVzdBogLnBsYXRvLkxpc3REZXRhaWxBbnN3ZXJzUmVzcG9uc2UiABJDCgxJbnNlcnRBbnN3ZXISGi5wbGF0by5JbnNlcnRBbnN3ZXJSZXF1ZXN0GhUucGxhdG8uQW5zd2VyUmVzcG9uc2UiABJDCgxVcGRhdGVBbnN3ZXISGi5wbGF0by5VcGRhdGVBbnN3ZXJSZXF1ZXN0GhUucGxhdG8uQW5zd2VyUmVzcG9uc2UiABI/CgxEZWxldGVBbnN3ZXISFi5wbGF0by5BbnN3ZXJJZFJlcXVlc3QaFS5jb3JlLkdlbmVyaWNSZXNwb25zZSIAEkoKDVNlYXJjaEFuc3dlcnMSGy5wbGF0by5TZWFyY2hBbnN3ZXJzUmVxdWVzdBoaLnBsYXRvLkxpc3RBbnN3ZXJzUmVzcG9uc2UiAEIRWg9wbGF0by9hcGkvcHJvdG9iBnByb3RvMw",
    [file_plato_generic, file_plato_object, file_core],
  );

/**
 * @generated from message plato.SearchAnswersRequest
 */
export type SearchAnswersRequest = Message<"plato.SearchAnswersRequest"> & {
  /**
   * @generated from field: core.BaseRequest base = 1;
   */
  base?: BaseRequest;

  /**
   * @generated from field: string query = 2;
   */
  query: string;

  /**
   * @generated from field: int32 topic_id = 3;
   */
  topicId: number;

  /**
   * @generated from field: int32 mode_id = 4;
   */
  modeId: number;
};

/**
 * Describes the message plato.SearchAnswersRequest.
 * Use `create(SearchAnswersRequestSchema)` to create a new message.
 */
export const SearchAnswersRequestSchema: GenMessage<SearchAnswersRequest> =
  /*@__PURE__*/
  messageDesc(file_plato_answer, 0);

/**
 * @generated from message plato.ListAnswersResponse
 */
export type ListAnswersResponse = Message<"plato.ListAnswersResponse"> & {
  /**
   * @generated from field: core.BaseResponse base = 1;
   */
  base?: BaseResponse;

  /**
   * @generated from field: repeated plato.Answer answers = 2;
   */
  answers: Answer[];
};

/**
 * Describes the message plato.ListAnswersResponse.
 * Use `create(ListAnswersResponseSchema)` to create a new message.
 */
export const ListAnswersResponseSchema: GenMessage<ListAnswersResponse> =
  /*@__PURE__*/
  messageDesc(file_plato_answer, 1);

/**
 * @generated from message plato.ListDetailAnswersResponse
 */
export type ListDetailAnswersResponse =
  Message<"plato.ListDetailAnswersResponse"> & {
    /**
     * @generated from field: core.BaseResponse base = 1;
     */
    base?: BaseResponse;

    /**
     * @generated from field: repeated plato.DetailAnswer detail_answers = 2;
     */
    detailAnswers: DetailAnswer[];
  };

/**
 * Describes the message plato.ListDetailAnswersResponse.
 * Use `create(ListDetailAnswersResponseSchema)` to create a new message.
 */
export const ListDetailAnswersResponseSchema: GenMessage<ListDetailAnswersResponse> =
  /*@__PURE__*/
  messageDesc(file_plato_answer, 2);

/**
 * @generated from message plato.AnswerResponse
 */
export type AnswerResponse = Message<"plato.AnswerResponse"> & {
  /**
   * @generated from field: core.BaseResponse base = 1;
   */
  base?: BaseResponse;

  /**
   * @generated from field: plato.Answer answer = 2;
   */
  answer?: Answer;
};

/**
 * Describes the message plato.AnswerResponse.
 * Use `create(AnswerResponseSchema)` to create a new message.
 */
export const AnswerResponseSchema: GenMessage<AnswerResponse> =
  /*@__PURE__*/
  messageDesc(file_plato_answer, 3);

/**
 * @generated from message plato.DetailAnswerResponse
 */
export type DetailAnswerResponse = Message<"plato.DetailAnswerResponse"> & {
  /**
   * @generated from field: core.BaseResponse base = 1;
   */
  base?: BaseResponse;

  /**
   * @generated from field: plato.DetailAnswer detail_answer = 2;
   */
  detailAnswer?: DetailAnswer;
};

/**
 * Describes the message plato.DetailAnswerResponse.
 * Use `create(DetailAnswerResponseSchema)` to create a new message.
 */
export const DetailAnswerResponseSchema: GenMessage<DetailAnswerResponse> =
  /*@__PURE__*/
  messageDesc(file_plato_answer, 4);

/**
 * @generated from message plato.InsertAnswerRequest
 */
export type InsertAnswerRequest = Message<"plato.InsertAnswerRequest"> & {
  /**
   * @generated from field: core.BaseRequest base = 1;
   */
  base?: BaseRequest;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: optional string icon_url = 3;
   */
  iconUrl?: string;

  /**
   * e.g., "Champion", "Hero", "Pokemon"
   *
   * @generated from field: string answer_type = 4;
   */
  answerType: string;

  /**
   * @generated from field: int32 topic_id = 10;
   */
  topicId: number;
};

/**
 * Describes the message plato.InsertAnswerRequest.
 * Use `create(InsertAnswerRequestSchema)` to create a new message.
 */
export const InsertAnswerRequestSchema: GenMessage<InsertAnswerRequest> =
  /*@__PURE__*/
  messageDesc(file_plato_answer, 5);

/**
 * @generated from message plato.UpdateAnswerRequest
 */
export type UpdateAnswerRequest = Message<"plato.UpdateAnswerRequest"> & {
  /**
   * @generated from field: core.BaseRequest base = 1;
   */
  base?: BaseRequest;

  /**
   * @generated from field: optional string name = 2;
   */
  name?: string;

  /**
   * @generated from field: optional string icon_url = 3;
   */
  iconUrl?: string;

  /**
   * e.g., "Champion", "Hero", "Pokemon"
   *
   * @generated from field: string answer_type = 4;
   */
  answerType: string;

  /**
   * @generated from field: int32 answer_id = 10;
   */
  answerId: number;
};

/**
 * Describes the message plato.UpdateAnswerRequest.
 * Use `create(UpdateAnswerRequestSchema)` to create a new message.
 */
export const UpdateAnswerRequestSchema: GenMessage<UpdateAnswerRequest> =
  /*@__PURE__*/
  messageDesc(file_plato_answer, 6);

/**
 * @generated from service plato.PlatoAnswerService
 */
export const PlatoAnswerService: GenService<{
  /**
   * @generated from rpc plato.PlatoAnswerService.GetAnswerById
   */
  getAnswerById: {
    methodKind: "unary";
    input: typeof AnswerIdRequestSchema;
    output: typeof AnswerResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoAnswerService.GetDetailAnswerById
   */
  getDetailAnswerById: {
    methodKind: "unary";
    input: typeof AnswerIdRequestSchema;
    output: typeof DetailAnswerResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoAnswerService.ListAnswersByTopicId
   */
  listAnswersByTopicId: {
    methodKind: "unary";
    input: typeof TopicIdRequestSchema;
    output: typeof ListAnswersResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoAnswerService.ListDetailAnswersByTopicId
   */
  listDetailAnswersByTopicId: {
    methodKind: "unary";
    input: typeof TopicIdRequestSchema;
    output: typeof ListDetailAnswersResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoAnswerService.InsertAnswer
   */
  insertAnswer: {
    methodKind: "unary";
    input: typeof InsertAnswerRequestSchema;
    output: typeof AnswerResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoAnswerService.UpdateAnswer
   */
  updateAnswer: {
    methodKind: "unary";
    input: typeof UpdateAnswerRequestSchema;
    output: typeof AnswerResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoAnswerService.DeleteAnswer
   */
  deleteAnswer: {
    methodKind: "unary";
    input: typeof AnswerIdRequestSchema;
    output: typeof GenericResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoAnswerService.SearchAnswers
   */
  searchAnswers: {
    methodKind: "unary";
    input: typeof SearchAnswersRequestSchema;
    output: typeof ListAnswersResponseSchema;
  };
}> = /*@__PURE__*/ serviceDesc(file_plato_answer, 0);
