// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file plato/answercategory.proto (package plato, syntax proto3)
/* eslint-disable */

import type {
  GenFile,
  GenMessage,
  GenService,
} from "@bufbuild/protobuf/codegenv2";
import {
  fileDesc,
  messageDesc,
  serviceDesc,
} from "@bufbuild/protobuf/codegenv2";
import type {
  BaseRequest,
  BaseResponse,
  GenericResponseSchema,
} from "../core/core_pb";
import { file_core_core } from "../core/core_pb";
import type {
  AnswerCategoryIdRequestSchema,
  AnswerIdRequestSchema,
} from "./generic_pb";
import { file_plato_generic } from "./generic_pb";
import type { AnswerCategory } from "./object_pb";
import { file_plato_object } from "./object_pb";

import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file plato/answercategory.proto.
 */
export const file_plato_answercategory: GenFile =
  /*@__PURE__*/
  fileDesc(
    "ChpwbGF0by9hbnN3ZXJjYXRlZ29yeS5wcm90bxIFcGxhdG8icgocTGlzdEFuc3dlckNhdGVnb3JpZXNSZXNwb25zZRIhCgRiYXNlGAEgASgLMhMucGxhdG8uQmFzZVJlc3BvbnNlEi8KEGFuc3dlckNhdGVnb3JpZXMYAiADKAsyFS5wbGF0by5BbnN3ZXJDYXRlZ29yeSJqChZBbnN3ZXJDYXRlZ29yeVJlc3BvbnNlEiEKBGJhc2UYASABKAsyEy5wbGF0by5CYXNlUmVzcG9uc2USLQoOYW5zd2VyQ2F0ZWdvcnkYAiABKAsyFS5wbGF0by5BbnN3ZXJDYXRlZ29yeSKFAQobSW5zZXJ0QW5zd2VyQ2F0ZWdvcnlSZXF1ZXN0EigKBGJhc2UYASABKAsyEi5wbGF0by5CYXNlUmVxdWVzdEIGukgDyAEBEgwKBG5hbWUYAiABKAkSDAoEdHlwZRgDIAEoCRINCgV2YWx1ZRgEIAEoCRIRCglhbnN3ZXJfaWQYBiABKAUiuQEKG1VwZGF0ZUFuc3dlckNhdGVnb3J5UmVxdWVzdBIoCgRiYXNlGAEgASgLMhIucGxhdG8uQmFzZVJlcXVlc3RCBrpIA8gBARIRCgRuYW1lGAIgASgJSACIAQESEQoEdHlwZRgDIAEoCUgBiAEBEhIKBXZhbHVlGAQgASgJSAKIAQESGgoSYW5zd2VyX2NhdGVnb3J5X2lkGAUgASgFQgcKBV9uYW1lQgcKBV90eXBlQggKBl92YWx1ZTLjAwoaUGxhdG9BbnN3ZXJDYXRlZ29yeVNlcnZpY2USWAoVR2V0QW5zd2VyQ2F0ZWdvcnlCeUlkEh4ucGxhdG8uQW5zd2VyQ2F0ZWdvcnlJZFJlcXVlc3QaHS5wbGF0by5BbnN3ZXJDYXRlZ29yeVJlc3BvbnNlIgASXwoeTGlzdEFuc3dlckNhdGVnb3JpZXNCeUFuc3dlcklkEhYucGxhdG8uQW5zd2VySWRSZXF1ZXN0GiMucGxhdG8uTGlzdEFuc3dlckNhdGVnb3JpZXNSZXNwb25zZSIAElsKFEluc2VydEFuc3dlckNhdGVnb3J5EiIucGxhdG8uSW5zZXJ0QW5zd2VyQ2F0ZWdvcnlSZXF1ZXN0Gh0ucGxhdG8uQW5zd2VyQ2F0ZWdvcnlSZXNwb25zZSIAElsKFFVwZGF0ZUFuc3dlckNhdGVnb3J5EiIucGxhdG8uVXBkYXRlQW5zd2VyQ2F0ZWdvcnlSZXF1ZXN0Gh0ucGxhdG8uQW5zd2VyQ2F0ZWdvcnlSZXNwb25zZSIAElAKFERlbGV0ZUFuc3dlckNhdGVnb3J5Eh4ucGxhdG8uQW5zd2VyQ2F0ZWdvcnlJZFJlcXVlc3QaFi5wbGF0by5HZW5lcmljUmVzcG9uc2UiAEIRWg9wbGF0by9hcGkvcHJvdG9iBnByb3RvMw",
    [file_core_core, file_plato_generic, file_plato_object],
  );

/**
 * @generated from message plato.ListAnswerCategoriesResponse
 */
export type ListAnswerCategoriesResponse =
  Message<"plato.ListAnswerCategoriesResponse"> & {
    /**
     * @generated from field: plato.BaseResponse base = 1;
     */
    base?: BaseResponse;

    /**
     * @generated from field: repeated plato.AnswerCategory answerCategories = 2;
     */
    answerCategories: AnswerCategory[];
  };

/**
 * Describes the message plato.ListAnswerCategoriesResponse.
 * Use `create(ListAnswerCategoriesResponseSchema)` to create a new message.
 */
export const ListAnswerCategoriesResponseSchema: GenMessage<ListAnswerCategoriesResponse> =
  /*@__PURE__*/
  messageDesc(file_plato_answercategory, 0);

/**
 * @generated from message plato.AnswerCategoryResponse
 */
export type AnswerCategoryResponse = Message<"plato.AnswerCategoryResponse"> & {
  /**
   * @generated from field: plato.BaseResponse base = 1;
   */
  base?: BaseResponse;

  /**
   * @generated from field: plato.AnswerCategory answerCategory = 2;
   */
  answerCategory?: AnswerCategory;
};

/**
 * Describes the message plato.AnswerCategoryResponse.
 * Use `create(AnswerCategoryResponseSchema)` to create a new message.
 */
export const AnswerCategoryResponseSchema: GenMessage<AnswerCategoryResponse> =
  /*@__PURE__*/
  messageDesc(file_plato_answercategory, 1);

/**
 * @generated from message plato.InsertAnswerCategoryRequest
 */
export type InsertAnswerCategoryRequest =
  Message<"plato.InsertAnswerCategoryRequest"> & {
    /**
     * @generated from field: plato.BaseRequest base = 1;
     */
    base?: BaseRequest;

    /**
     * @generated from field: string name = 2;
     */
    name: string;

    /**
     * @generated from field: string type = 3;
     */
    type: string;

    /**
     * @generated from field: string value = 4;
     */
    value: string;

    /**
     * @generated from field: int32 answer_id = 6;
     */
    answerId: number;
  };

/**
 * Describes the message plato.InsertAnswerCategoryRequest.
 * Use `create(InsertAnswerCategoryRequestSchema)` to create a new message.
 */
export const InsertAnswerCategoryRequestSchema: GenMessage<InsertAnswerCategoryRequest> =
  /*@__PURE__*/
  messageDesc(file_plato_answercategory, 2);

/**
 * @generated from message plato.UpdateAnswerCategoryRequest
 */
export type UpdateAnswerCategoryRequest =
  Message<"plato.UpdateAnswerCategoryRequest"> & {
    /**
     * @generated from field: plato.BaseRequest base = 1;
     */
    base?: BaseRequest;

    /**
     * @generated from field: optional string name = 2;
     */
    name?: string;

    /**
     * @generated from field: optional string type = 3;
     */
    type?: string;

    /**
     * @generated from field: optional string value = 4;
     */
    value?: string;

    /**
     * @generated from field: int32 answer_category_id = 5;
     */
    answerCategoryId: number;
  };

/**
 * Describes the message plato.UpdateAnswerCategoryRequest.
 * Use `create(UpdateAnswerCategoryRequestSchema)` to create a new message.
 */
export const UpdateAnswerCategoryRequestSchema: GenMessage<UpdateAnswerCategoryRequest> =
  /*@__PURE__*/
  messageDesc(file_plato_answercategory, 3);

/**
 * @generated from service plato.PlatoAnswerCategoryService
 */
export const PlatoAnswerCategoryService: GenService<{
  /**
   * @generated from rpc plato.PlatoAnswerCategoryService.GetAnswerCategoryById
   */
  getAnswerCategoryById: {
    methodKind: "unary";
    input: typeof AnswerCategoryIdRequestSchema;
    output: typeof AnswerCategoryResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoAnswerCategoryService.ListAnswerCategoriesByAnswerId
   */
  listAnswerCategoriesByAnswerId: {
    methodKind: "unary";
    input: typeof AnswerIdRequestSchema;
    output: typeof ListAnswerCategoriesResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoAnswerCategoryService.InsertAnswerCategory
   */
  insertAnswerCategory: {
    methodKind: "unary";
    input: typeof InsertAnswerCategoryRequestSchema;
    output: typeof AnswerCategoryResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoAnswerCategoryService.UpdateAnswerCategory
   */
  updateAnswerCategory: {
    methodKind: "unary";
    input: typeof UpdateAnswerCategoryRequestSchema;
    output: typeof AnswerCategoryResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoAnswerCategoryService.DeleteAnswerCategory
   */
  deleteAnswerCategory: {
    methodKind: "unary";
    input: typeof AnswerCategoryIdRequestSchema;
    output: typeof GenericResponseSchema;
  };
}> = /*@__PURE__*/ serviceDesc(file_plato_answercategory, 0);
