// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file plato/answercategory.proto (package plato, syntax proto3)
/* eslint-disable */

import type {
  GenFile,
  GenMessage,
  GenService,
} from "@bufbuild/protobuf/codegenv2";
import {
  fileDesc,
  messageDesc,
  serviceDesc,
} from "@bufbuild/protobuf/codegenv2";
import type {
  BaseRequest,
  BaseResponse,
  GenericResponseSchema,
} from "../core_pb";
import { file_core } from "../core_pb";
import type {
  AnswerCategoryIdRequestSchema,
  AnswerIdRequestSchema,
} from "./generic_pb";
import { file_plato_generic } from "./generic_pb";
import type { AnswerCategory } from "./object_pb";
import { file_plato_object } from "./object_pb";

import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file plato/answercategory.proto.
 */
export const file_plato_answercategory: GenFile =
  /*@__PURE__*/
  fileDesc(
    "ChpwbGF0by9hbnN3ZXJjYXRlZ29yeS5wcm90bxIFcGxhdG8icQocTGlzdEFuc3dlckNhdGVnb3JpZXNSZXNwb25zZRIgCgRiYXNlGAEgASgLMhIuY29yZS5CYXNlUmVzcG9uc2USLwoQYW5zd2VyQ2F0ZWdvcmllcxgCIAMoCzIVLnBsYXRvLkFuc3dlckNhdGVnb3J5ImkKFkFuc3dlckNhdGVnb3J5UmVzcG9uc2USIAoEYmFzZRgBIAEoCzISLmNvcmUuQmFzZVJlc3BvbnNlEi0KDmFuc3dlckNhdGVnb3J5GAIgASgLMhUucGxhdG8uQW5zd2VyQ2F0ZWdvcnkihAEKG0luc2VydEFuc3dlckNhdGVnb3J5UmVxdWVzdBInCgRiYXNlGAEgASgLMhEuY29yZS5CYXNlUmVxdWVzdEIGukgDyAEBEgwKBG5hbWUYAiABKAkSDAoEdHlwZRgDIAEoCRINCgV2YWx1ZRgEIAEoCRIRCglhbnN3ZXJfaWQYBiABKAUiuAEKG1VwZGF0ZUFuc3dlckNhdGVnb3J5UmVxdWVzdBInCgRiYXNlGAEgASgLMhEuY29yZS5CYXNlUmVxdWVzdEIGukgDyAEBEhEKBG5hbWUYAiABKAlIAIgBARIRCgR0eXBlGAMgASgJSAGIAQESEgoFdmFsdWUYBCABKAlIAogBARIaChJhbnN3ZXJfY2F0ZWdvcnlfaWQYBSABKAVCBwoFX25hbWVCBwoFX3R5cGVCCAoGX3ZhbHVlMuIDChpQbGF0b0Fuc3dlckNhdGVnb3J5U2VydmljZRJYChVHZXRBbnN3ZXJDYXRlZ29yeUJ5SWQSHi5wbGF0by5BbnN3ZXJDYXRlZ29yeUlkUmVxdWVzdBodLnBsYXRvLkFuc3dlckNhdGVnb3J5UmVzcG9uc2UiABJfCh5MaXN0QW5zd2VyQ2F0ZWdvcmllc0J5QW5zd2VySWQSFi5wbGF0by5BbnN3ZXJJZFJlcXVlc3QaIy5wbGF0by5MaXN0QW5zd2VyQ2F0ZWdvcmllc1Jlc3BvbnNlIgASWwoUSW5zZXJ0QW5zd2VyQ2F0ZWdvcnkSIi5wbGF0by5JbnNlcnRBbnN3ZXJDYXRlZ29yeVJlcXVlc3QaHS5wbGF0by5BbnN3ZXJDYXRlZ29yeVJlc3BvbnNlIgASWwoUVXBkYXRlQW5zd2VyQ2F0ZWdvcnkSIi5wbGF0by5VcGRhdGVBbnN3ZXJDYXRlZ29yeVJlcXVlc3QaHS5wbGF0by5BbnN3ZXJDYXRlZ29yeVJlc3BvbnNlIgASTwoURGVsZXRlQW5zd2VyQ2F0ZWdvcnkSHi5wbGF0by5BbnN3ZXJDYXRlZ29yeUlkUmVxdWVzdBoVLmNvcmUuR2VuZXJpY1Jlc3BvbnNlIgBCEVoPcGxhdG8vYXBpL3Byb3RvYgZwcm90bzM",
    [file_core, file_plato_generic, file_plato_object],
  );

/**
 * @generated from message plato.ListAnswerCategoriesResponse
 */
export type ListAnswerCategoriesResponse =
  Message<"plato.ListAnswerCategoriesResponse"> & {
    /**
     * @generated from field: core.BaseResponse base = 1;
     */
    base?: BaseResponse;

    /**
     * @generated from field: repeated plato.AnswerCategory answerCategories = 2;
     */
    answerCategories: AnswerCategory[];
  };

/**
 * Describes the message plato.ListAnswerCategoriesResponse.
 * Use `create(ListAnswerCategoriesResponseSchema)` to create a new message.
 */
export const ListAnswerCategoriesResponseSchema: GenMessage<ListAnswerCategoriesResponse> =
  /*@__PURE__*/
  messageDesc(file_plato_answercategory, 0);

/**
 * @generated from message plato.AnswerCategoryResponse
 */
export type AnswerCategoryResponse = Message<"plato.AnswerCategoryResponse"> & {
  /**
   * @generated from field: core.BaseResponse base = 1;
   */
  base?: BaseResponse;

  /**
   * @generated from field: plato.AnswerCategory answerCategory = 2;
   */
  answerCategory?: AnswerCategory;
};

/**
 * Describes the message plato.AnswerCategoryResponse.
 * Use `create(AnswerCategoryResponseSchema)` to create a new message.
 */
export const AnswerCategoryResponseSchema: GenMessage<AnswerCategoryResponse> =
  /*@__PURE__*/
  messageDesc(file_plato_answercategory, 1);

/**
 * @generated from message plato.InsertAnswerCategoryRequest
 */
export type InsertAnswerCategoryRequest =
  Message<"plato.InsertAnswerCategoryRequest"> & {
    /**
     * @generated from field: core.BaseRequest base = 1;
     */
    base?: BaseRequest;

    /**
     * @generated from field: string name = 2;
     */
    name: string;

    /**
     * @generated from field: string type = 3;
     */
    type: string;

    /**
     * @generated from field: string value = 4;
     */
    value: string;

    /**
     * @generated from field: int32 answer_id = 6;
     */
    answerId: number;
  };

/**
 * Describes the message plato.InsertAnswerCategoryRequest.
 * Use `create(InsertAnswerCategoryRequestSchema)` to create a new message.
 */
export const InsertAnswerCategoryRequestSchema: GenMessage<InsertAnswerCategoryRequest> =
  /*@__PURE__*/
  messageDesc(file_plato_answercategory, 2);

/**
 * @generated from message plato.UpdateAnswerCategoryRequest
 */
export type UpdateAnswerCategoryRequest =
  Message<"plato.UpdateAnswerCategoryRequest"> & {
    /**
     * @generated from field: core.BaseRequest base = 1;
     */
    base?: BaseRequest;

    /**
     * @generated from field: optional string name = 2;
     */
    name?: string;

    /**
     * @generated from field: optional string type = 3;
     */
    type?: string;

    /**
     * @generated from field: optional string value = 4;
     */
    value?: string;

    /**
     * @generated from field: int32 answer_category_id = 5;
     */
    answerCategoryId: number;
  };

/**
 * Describes the message plato.UpdateAnswerCategoryRequest.
 * Use `create(UpdateAnswerCategoryRequestSchema)` to create a new message.
 */
export const UpdateAnswerCategoryRequestSchema: GenMessage<UpdateAnswerCategoryRequest> =
  /*@__PURE__*/
  messageDesc(file_plato_answercategory, 3);

/**
 * @generated from service plato.PlatoAnswerCategoryService
 */
export const PlatoAnswerCategoryService: GenService<{
  /**
   * @generated from rpc plato.PlatoAnswerCategoryService.GetAnswerCategoryById
   */
  getAnswerCategoryById: {
    methodKind: "unary";
    input: typeof AnswerCategoryIdRequestSchema;
    output: typeof AnswerCategoryResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoAnswerCategoryService.ListAnswerCategoriesByAnswerId
   */
  listAnswerCategoriesByAnswerId: {
    methodKind: "unary";
    input: typeof AnswerIdRequestSchema;
    output: typeof ListAnswerCategoriesResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoAnswerCategoryService.InsertAnswerCategory
   */
  insertAnswerCategory: {
    methodKind: "unary";
    input: typeof InsertAnswerCategoryRequestSchema;
    output: typeof AnswerCategoryResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoAnswerCategoryService.UpdateAnswerCategory
   */
  updateAnswerCategory: {
    methodKind: "unary";
    input: typeof UpdateAnswerCategoryRequestSchema;
    output: typeof AnswerCategoryResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoAnswerCategoryService.DeleteAnswerCategory
   */
  deleteAnswerCategory: {
    methodKind: "unary";
    input: typeof AnswerCategoryIdRequestSchema;
    output: typeof GenericResponseSchema;
  };
}> = /*@__PURE__*/ serviceDesc(file_plato_answercategory, 0);
