// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file plato/answer.proto (package plato, syntax proto3)
/* eslint-disable */

import type {
  GenFile,
  GenMessage,
  GenService,
} from "@bufbuild/protobuf/codegenv2";
import {
  fileDesc,
  messageDesc,
  serviceDesc,
} from "@bufbuild/protobuf/codegenv2";
import type {
  BaseRequest,
  BaseResponse,
  GenericResponseSchema,
} from "../core/core_pb";
import { file_core_core } from "../core/core_pb";
import type { AnswerIdRequestSchema, TopicIdRequestSchema } from "./generic_pb";
import { file_plato_generic } from "./generic_pb";
import type { Answer, DetailAnswer } from "./object_pb";
import { file_plato_object } from "./object_pb";

import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file plato/answer.proto.
 */
export const file_plato_answer: GenFile =
  /*@__PURE__*/
  fileDesc(
    "ChJwbGF0by9hbnN3ZXIucHJvdG8SBXBsYXRvInUKFFNlYXJjaEFuc3dlcnNSZXF1ZXN0EiAKBGJhc2UYASABKAsyEi5wbGF0by5CYXNlUmVxdWVzdBIYCgVxdWVyeRgCIAEoCUIJukgGcgQQARhkEhAKCHRvcGljX2lkGAMgASgFEg8KB21vZGVfaWQYBCABKAUiWAoTTGlzdEFuc3dlcnNSZXNwb25zZRIhCgRiYXNlGAEgASgLMhMucGxhdG8uQmFzZVJlc3BvbnNlEh4KB2Fuc3dlcnMYAiADKAsyDS5wbGF0by5BbnN3ZXIiawoZTGlzdERldGFpbEFuc3dlcnNSZXNwb25zZRIhCgRiYXNlGAEgASgLMhMucGxhdG8uQmFzZVJlc3BvbnNlEisKDmRldGFpbF9hbnN3ZXJzGAIgAygLMhMucGxhdG8uRGV0YWlsQW5zd2VyIlIKDkFuc3dlclJlc3BvbnNlEiEKBGJhc2UYASABKAsyEy5wbGF0by5CYXNlUmVzcG9uc2USHQoGYW5zd2VyGAIgASgLMg0ucGxhdG8uQW5zd2VyImUKFERldGFpbEFuc3dlclJlc3BvbnNlEiEKBGJhc2UYASABKAsyEy5wbGF0by5CYXNlUmVzcG9uc2USKgoNZGV0YWlsX2Fuc3dlchgCIAEoCzITLnBsYXRvLkRldGFpbEFuc3dlciKDAQoTSW5zZXJ0QW5zd2VyUmVxdWVzdBIoCgRiYXNlGAEgASgLMhIucGxhdG8uQmFzZVJlcXVlc3RCBrpIA8gBARIMCgRuYW1lGAIgASgJEhUKCGljb25fdXJsGAMgASgJSACIAQESEAoIdG9waWNfaWQYBCABKAVCCwoJX2ljb25fdXJsIpIBChNVcGRhdGVBbnN3ZXJSZXF1ZXN0EigKBGJhc2UYASABKAsyEi5wbGF0by5CYXNlUmVxdWVzdEIGukgDyAEBEhEKBG5hbWUYAiABKAlIAIgBARIVCghpY29uX3VybBgDIAEoCUgBiAEBEhEKCWFuc3dlcl9pZBgEIAEoBUIHCgVfbmFtZUILCglfaWNvbl91cmwy4gQKElBsYXRvQW5zd2VyU2VydmljZRJACg1HZXRBbnN3ZXJCeUlkEhYucGxhdG8uQW5zd2VySWRSZXF1ZXN0GhUucGxhdG8uQW5zd2VyUmVzcG9uc2UiABJMChNHZXREZXRhaWxBbnN3ZXJCeUlkEhYucGxhdG8uQW5zd2VySWRSZXF1ZXN0GhsucGxhdG8uRGV0YWlsQW5zd2VyUmVzcG9uc2UiABJLChRMaXN0QW5zd2Vyc0J5VG9waWNJZBIVLnBsYXRvLlRvcGljSWRSZXF1ZXN0GhoucGxhdG8uTGlzdEFuc3dlcnNSZXNwb25zZSIAElcKGkxpc3REZXRhaWxBbnN3ZXJzQnlUb3BpY0lkEhUucGxhdG8uVG9waWNJZFJlcXVlc3QaIC5wbGF0by5MaXN0RGV0YWlsQW5zd2Vyc1Jlc3BvbnNlIgASQwoMSW5zZXJ0QW5zd2VyEhoucGxhdG8uSW5zZXJ0QW5zd2VyUmVxdWVzdBoVLnBsYXRvLkFuc3dlclJlc3BvbnNlIgASQwoMVXBkYXRlQW5zd2VyEhoucGxhdG8uVXBkYXRlQW5zd2VyUmVxdWVzdBoVLnBsYXRvLkFuc3dlclJlc3BvbnNlIgASQAoMRGVsZXRlQW5zd2VyEhYucGxhdG8uQW5zd2VySWRSZXF1ZXN0GhYucGxhdG8uR2VuZXJpY1Jlc3BvbnNlIgASSgoNU2VhcmNoQW5zd2VycxIbLnBsYXRvLlNlYXJjaEFuc3dlcnNSZXF1ZXN0GhoucGxhdG8uTGlzdEFuc3dlcnNSZXNwb25zZSIAQhFaD3BsYXRvL2FwaS9wcm90b2IGcHJvdG8z",
    [file_core_core, file_plato_generic, file_plato_object],
  );

/**
 * @generated from message plato.SearchAnswersRequest
 */
export type SearchAnswersRequest = Message<"plato.SearchAnswersRequest"> & {
  /**
   * @generated from field: plato.BaseRequest base = 1;
   */
  base?: BaseRequest;

  /**
   * @generated from field: string query = 2;
   */
  query: string;

  /**
   * @generated from field: int32 topic_id = 3;
   */
  topicId: number;

  /**
   * @generated from field: int32 mode_id = 4;
   */
  modeId: number;
};

/**
 * Describes the message plato.SearchAnswersRequest.
 * Use `create(SearchAnswersRequestSchema)` to create a new message.
 */
export const SearchAnswersRequestSchema: GenMessage<SearchAnswersRequest> =
  /*@__PURE__*/
  messageDesc(file_plato_answer, 0);

/**
 * @generated from message plato.ListAnswersResponse
 */
export type ListAnswersResponse = Message<"plato.ListAnswersResponse"> & {
  /**
   * @generated from field: plato.BaseResponse base = 1;
   */
  base?: BaseResponse;

  /**
   * @generated from field: repeated plato.Answer answers = 2;
   */
  answers: Answer[];
};

/**
 * Describes the message plato.ListAnswersResponse.
 * Use `create(ListAnswersResponseSchema)` to create a new message.
 */
export const ListAnswersResponseSchema: GenMessage<ListAnswersResponse> =
  /*@__PURE__*/
  messageDesc(file_plato_answer, 1);

/**
 * @generated from message plato.ListDetailAnswersResponse
 */
export type ListDetailAnswersResponse =
  Message<"plato.ListDetailAnswersResponse"> & {
    /**
     * @generated from field: plato.BaseResponse base = 1;
     */
    base?: BaseResponse;

    /**
     * @generated from field: repeated plato.DetailAnswer detail_answers = 2;
     */
    detailAnswers: DetailAnswer[];
  };

/**
 * Describes the message plato.ListDetailAnswersResponse.
 * Use `create(ListDetailAnswersResponseSchema)` to create a new message.
 */
export const ListDetailAnswersResponseSchema: GenMessage<ListDetailAnswersResponse> =
  /*@__PURE__*/
  messageDesc(file_plato_answer, 2);

/**
 * @generated from message plato.AnswerResponse
 */
export type AnswerResponse = Message<"plato.AnswerResponse"> & {
  /**
   * @generated from field: plato.BaseResponse base = 1;
   */
  base?: BaseResponse;

  /**
   * @generated from field: plato.Answer answer = 2;
   */
  answer?: Answer;
};

/**
 * Describes the message plato.AnswerResponse.
 * Use `create(AnswerResponseSchema)` to create a new message.
 */
export const AnswerResponseSchema: GenMessage<AnswerResponse> =
  /*@__PURE__*/
  messageDesc(file_plato_answer, 3);

/**
 * @generated from message plato.DetailAnswerResponse
 */
export type DetailAnswerResponse = Message<"plato.DetailAnswerResponse"> & {
  /**
   * @generated from field: plato.BaseResponse base = 1;
   */
  base?: BaseResponse;

  /**
   * @generated from field: plato.DetailAnswer detail_answer = 2;
   */
  detailAnswer?: DetailAnswer;
};

/**
 * Describes the message plato.DetailAnswerResponse.
 * Use `create(DetailAnswerResponseSchema)` to create a new message.
 */
export const DetailAnswerResponseSchema: GenMessage<DetailAnswerResponse> =
  /*@__PURE__*/
  messageDesc(file_plato_answer, 4);

/**
 * @generated from message plato.InsertAnswerRequest
 */
export type InsertAnswerRequest = Message<"plato.InsertAnswerRequest"> & {
  /**
   * @generated from field: plato.BaseRequest base = 1;
   */
  base?: BaseRequest;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: optional string icon_url = 3;
   */
  iconUrl?: string;

  /**
   * @generated from field: int32 topic_id = 4;
   */
  topicId: number;
};

/**
 * Describes the message plato.InsertAnswerRequest.
 * Use `create(InsertAnswerRequestSchema)` to create a new message.
 */
export const InsertAnswerRequestSchema: GenMessage<InsertAnswerRequest> =
  /*@__PURE__*/
  messageDesc(file_plato_answer, 5);

/**
 * @generated from message plato.UpdateAnswerRequest
 */
export type UpdateAnswerRequest = Message<"plato.UpdateAnswerRequest"> & {
  /**
   * @generated from field: plato.BaseRequest base = 1;
   */
  base?: BaseRequest;

  /**
   * @generated from field: optional string name = 2;
   */
  name?: string;

  /**
   * @generated from field: optional string icon_url = 3;
   */
  iconUrl?: string;

  /**
   * @generated from field: int32 answer_id = 4;
   */
  answerId: number;
};

/**
 * Describes the message plato.UpdateAnswerRequest.
 * Use `create(UpdateAnswerRequestSchema)` to create a new message.
 */
export const UpdateAnswerRequestSchema: GenMessage<UpdateAnswerRequest> =
  /*@__PURE__*/
  messageDesc(file_plato_answer, 6);

/**
 * @generated from service plato.PlatoAnswerService
 */
export const PlatoAnswerService: GenService<{
  /**
   * @generated from rpc plato.PlatoAnswerService.GetAnswerById
   */
  getAnswerById: {
    methodKind: "unary";
    input: typeof AnswerIdRequestSchema;
    output: typeof AnswerResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoAnswerService.GetDetailAnswerById
   */
  getDetailAnswerById: {
    methodKind: "unary";
    input: typeof AnswerIdRequestSchema;
    output: typeof DetailAnswerResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoAnswerService.ListAnswersByTopicId
   */
  listAnswersByTopicId: {
    methodKind: "unary";
    input: typeof TopicIdRequestSchema;
    output: typeof ListAnswersResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoAnswerService.ListDetailAnswersByTopicId
   */
  listDetailAnswersByTopicId: {
    methodKind: "unary";
    input: typeof TopicIdRequestSchema;
    output: typeof ListDetailAnswersResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoAnswerService.InsertAnswer
   */
  insertAnswer: {
    methodKind: "unary";
    input: typeof InsertAnswerRequestSchema;
    output: typeof AnswerResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoAnswerService.UpdateAnswer
   */
  updateAnswer: {
    methodKind: "unary";
    input: typeof UpdateAnswerRequestSchema;
    output: typeof AnswerResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoAnswerService.DeleteAnswer
   */
  deleteAnswer: {
    methodKind: "unary";
    input: typeof AnswerIdRequestSchema;
    output: typeof GenericResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoAnswerService.SearchAnswers
   */
  searchAnswers: {
    methodKind: "unary";
    input: typeof SearchAnswersRequestSchema;
    output: typeof ListAnswersResponseSchema;
  };
}> = /*@__PURE__*/ serviceDesc(file_plato_answer, 0);
