// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file plato/mode.proto (package plato, syntax proto3)
/* eslint-disable */

import type {
  GenFile,
  GenMessage,
  GenService,
} from "@bufbuild/protobuf/codegenv2";
import {
  fileDesc,
  messageDesc,
  serviceDesc,
} from "@bufbuild/protobuf/codegenv2";
import type {
  BaseRequest,
  BaseResponse,
  GenericResponseSchema,
} from "../core_pb";
import { file_core } from "../core_pb";
import type { ModeIdRequestSchema, TopicIdRequestSchema } from "./generic_pb";
import { file_plato_generic } from "./generic_pb";
import type { DailyGameGuessStats, Mode } from "./object_pb";
import { file_plato_object } from "./object_pb";

import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file plato/mode.proto.
 */
export const file_plato_mode: GenFile =
  /*@__PURE__*/
  fileDesc(
    "ChBwbGF0by9tb2RlLnByb3RvEgVwbGF0byJRChFMaXN0TW9kZXNSZXNwb25zZRIgCgRiYXNlGAEgASgLMhIuY29yZS5CYXNlUmVzcG9uc2USGgoFbW9kZXMYAiADKAsyCy5wbGF0by5Nb2RlIqYBCgxNb2RlUmVzcG9uc2USIAoEYmFzZRgBIAEoCzISLmNvcmUuQmFzZVJlc3BvbnNlEhkKBG1vZGUYAiABKAsyCy5wbGF0by5Nb2RlEh0KFWN1cnJlbnRfZGFpbHlfZ2FtZV9pZBgDIAEoBRI6ChZkYWlseV9nYW1lX2d1ZXNzX3N0YXRzGAQgASgLMhoucGxhdG8uRGFpbHlHYW1lR3Vlc3NTdGF0cyKmAQoRSW5zZXJ0TW9kZVJlcXVlc3QSJwoEYmFzZRgBIAEoCzIRLmNvcmUuQmFzZVJlcXVlc3RCBrpIA8gBARINCgV0aXRsZRgCIAEoCRITCgtkZXNjcmlwdGlvbhgDIAEoCRIQCghpY29uX3VybBgEIAEoCRISCgpiYW5uZXJfdXJsGAUgASgJEgwKBHNsdWcYBiABKAkSEAoIdG9waWNfaWQYByABKAUi3AEKEVVwZGF0ZU1vZGVSZXF1ZXN0EicKBGJhc2UYASABKAsyES5jb3JlLkJhc2VSZXF1ZXN0Qga6SAPIAQESCgoCaWQYAiABKAUSEgoFdGl0bGUYAyABKAlIAIgBARIYCgtkZXNjcmlwdGlvbhgEIAEoCUgBiAEBEhUKCGljb25fdXJsGAUgASgJSAKIAQESFwoKYmFubmVyX3VybBgGIAEoCUgDiAEBQggKBl90aXRsZUIOCgxfZGVzY3JpcHRpb25CCwoJX2ljb25fdXJsQg0KC19iYW5uZXJfdXJsMtICChBQbGF0b01vZGVTZXJ2aWNlEjoKC0dldE1vZGVCeUlkEhQucGxhdG8uTW9kZUlkUmVxdWVzdBoTLnBsYXRvLk1vZGVSZXNwb25zZSIAEj0KCkluc2VydE1vZGUSGC5wbGF0by5JbnNlcnRNb2RlUmVxdWVzdBoTLnBsYXRvLk1vZGVSZXNwb25zZSIAEj0KClVwZGF0ZU1vZGUSGC5wbGF0by5VcGRhdGVNb2RlUmVxdWVzdBoTLnBsYXRvLk1vZGVSZXNwb25zZSIAEjsKCkRlbGV0ZU1vZGUSFC5wbGF0by5Nb2RlSWRSZXF1ZXN0GhUuY29yZS5HZW5lcmljUmVzcG9uc2UiABJHChJMaXN0TW9kZXNCeVRvcGljSWQSFS5wbGF0by5Ub3BpY0lkUmVxdWVzdBoYLnBsYXRvLkxpc3RNb2Rlc1Jlc3BvbnNlIgBCEVoPcGxhdG8vYXBpL3Byb3RvYgZwcm90bzM",
    [file_core, file_plato_generic, file_plato_object],
  );

/**
 * @generated from message plato.ListModesResponse
 */
export type ListModesResponse = Message<"plato.ListModesResponse"> & {
  /**
   * @generated from field: core.BaseResponse base = 1;
   */
  base?: BaseResponse;

  /**
   * @generated from field: repeated plato.Mode modes = 2;
   */
  modes: Mode[];
};

/**
 * Describes the message plato.ListModesResponse.
 * Use `create(ListModesResponseSchema)` to create a new message.
 */
export const ListModesResponseSchema: GenMessage<ListModesResponse> =
  /*@__PURE__*/
  messageDesc(file_plato_mode, 0);

/**
 * @generated from message plato.ModeResponse
 */
export type ModeResponse = Message<"plato.ModeResponse"> & {
  /**
   * @generated from field: core.BaseResponse base = 1;
   */
  base?: BaseResponse;

  /**
   * @generated from field: plato.Mode mode = 2;
   */
  mode?: Mode;

  /**
   * @generated from field: int32 current_daily_game_id = 3;
   */
  currentDailyGameId: number;

  /**
   * @generated from field: plato.DailyGameGuessStats daily_game_guess_stats = 4;
   */
  dailyGameGuessStats?: DailyGameGuessStats;
};

/**
 * Describes the message plato.ModeResponse.
 * Use `create(ModeResponseSchema)` to create a new message.
 */
export const ModeResponseSchema: GenMessage<ModeResponse> =
  /*@__PURE__*/
  messageDesc(file_plato_mode, 1);

/**
 * @generated from message plato.InsertModeRequest
 */
export type InsertModeRequest = Message<"plato.InsertModeRequest"> & {
  /**
   * @generated from field: core.BaseRequest base = 1;
   */
  base?: BaseRequest;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * @generated from field: string icon_url = 4;
   */
  iconUrl: string;

  /**
   * @generated from field: string banner_url = 5;
   */
  bannerUrl: string;

  /**
   * @generated from field: string slug = 6;
   */
  slug: string;

  /**
   * @generated from field: int32 topic_id = 7;
   */
  topicId: number;
};

/**
 * Describes the message plato.InsertModeRequest.
 * Use `create(InsertModeRequestSchema)` to create a new message.
 */
export const InsertModeRequestSchema: GenMessage<InsertModeRequest> =
  /*@__PURE__*/
  messageDesc(file_plato_mode, 2);

/**
 * @generated from message plato.UpdateModeRequest
 */
export type UpdateModeRequest = Message<"plato.UpdateModeRequest"> & {
  /**
   * @generated from field: core.BaseRequest base = 1;
   */
  base?: BaseRequest;

  /**
   * @generated from field: int32 id = 2;
   */
  id: number;

  /**
   * @generated from field: optional string title = 3;
   */
  title?: string;

  /**
   * @generated from field: optional string description = 4;
   */
  description?: string;

  /**
   * @generated from field: optional string icon_url = 5;
   */
  iconUrl?: string;

  /**
   * @generated from field: optional string banner_url = 6;
   */
  bannerUrl?: string;
};

/**
 * Describes the message plato.UpdateModeRequest.
 * Use `create(UpdateModeRequestSchema)` to create a new message.
 */
export const UpdateModeRequestSchema: GenMessage<UpdateModeRequest> =
  /*@__PURE__*/
  messageDesc(file_plato_mode, 3);

/**
 * @generated from service plato.PlatoModeService
 */
export const PlatoModeService: GenService<{
  /**
   * @generated from rpc plato.PlatoModeService.GetModeById
   */
  getModeById: {
    methodKind: "unary";
    input: typeof ModeIdRequestSchema;
    output: typeof ModeResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoModeService.InsertMode
   */
  insertMode: {
    methodKind: "unary";
    input: typeof InsertModeRequestSchema;
    output: typeof ModeResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoModeService.UpdateMode
   */
  updateMode: {
    methodKind: "unary";
    input: typeof UpdateModeRequestSchema;
    output: typeof ModeResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoModeService.DeleteMode
   */
  deleteMode: {
    methodKind: "unary";
    input: typeof ModeIdRequestSchema;
    output: typeof GenericResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoModeService.ListModesByTopicId
   */
  listModesByTopicId: {
    methodKind: "unary";
    input: typeof TopicIdRequestSchema;
    output: typeof ListModesResponseSchema;
  };
}> = /*@__PURE__*/ serviceDesc(file_plato_mode, 0);
