// @generated by protoc-gen-es v2.5.2 with parameter "target=ts"
// @generated from file plato/topic.proto (package plato, syntax proto3)
/* eslint-disable */

import type {
  GenFile,
  GenMessage,
  GenService,
} from "@bufbuild/protobuf/codegenv2";
import {
  fileDesc,
  messageDesc,
  serviceDesc,
} from "@bufbuild/protobuf/codegenv2";
import type {
  BaseRequest,
  BaseResponse,
  GenericResponseSchema,
} from "../core/core_pb";
import { file_core_core } from "../core/core_pb";
import type {
  PaginateRequestSchema,
  SlugRequestSchema,
  TopicIdRequestSchema,
} from "./generic_pb";
import { file_plato_generic } from "./generic_pb";
import type { Topic } from "./object_pb";
import { file_plato_object } from "./object_pb";

import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file plato/topic.proto.
 */
export const file_plato_topic: GenFile =
  /*@__PURE__*/
  fileDesc(
    "ChFwbGF0by90b3BpYy5wcm90bxIFcGxhdG8iWAoVUGFnaW5hdGVUb3BpY1Jlc3BvbnNlEiEKBGJhc2UYASABKAsyEy5wbGF0by5CYXNlUmVzcG9uc2USHAoGdG9waWNzGAIgAygLMgwucGxhdG8uVG9waWMiTwoNVG9waWNSZXNwb25zZRIhCgRiYXNlGAEgASgLMhMucGxhdG8uQmFzZVJlc3BvbnNlEhsKBXRvcGljGAIgASgLMgwucGxhdG8uVG9waWMilgEKEkluc2VydFRvcGljUmVxdWVzdBIoCgRiYXNlGAEgASgLMhIucGxhdG8uQmFzZVJlcXVlc3RCBrpIA8gBARINCgV0aXRsZRgCIAEoCRITCgtkZXNjcmlwdGlvbhgDIAEoCRIQCghpY29uX3VybBgEIAEoCRISCgpiYW5uZXJfdXJsGAUgASgJEgwKBHNsdWcYBiABKAki3gEKElVwZGF0ZVRvcGljUmVxdWVzdBIoCgRiYXNlGAEgASgLMhIucGxhdG8uQmFzZVJlcXVlc3RCBrpIA8gBARIKCgJpZBgCIAEoBBISCgV0aXRsZRgDIAEoCUgAiAEBEhgKC2Rlc2NyaXB0aW9uGAQgASgJSAGIAQESFQoIaWNvbl91cmwYBSABKAlIAogBARIXCgpiYW5uZXJfdXJsGAYgASgJSAOIAQFCCAoGX3RpdGxlQg4KDF9kZXNjcmlwdGlvbkILCglfaWNvbl91cmxCDQoLX2Jhbm5lcl91cmwynQMKEVBsYXRvVG9waWNTZXJ2aWNlEkAKC0luc2VydFRvcGljEhkucGxhdG8uSW5zZXJ0VG9waWNSZXF1ZXN0GhQucGxhdG8uVG9waWNSZXNwb25zZSIAEkAKC1VwZGF0ZVRvcGljEhkucGxhdG8uVXBkYXRlVG9waWNSZXF1ZXN0GhQucGxhdG8uVG9waWNSZXNwb25zZSIAEj4KC0RlbGV0ZVRvcGljEhUucGxhdG8uVG9waWNJZFJlcXVlc3QaFi5wbGF0by5HZW5lcmljUmVzcG9uc2UiABJHCg1QYWdpbmF0ZVRvcGljEhYucGxhdG8uUGFnaW5hdGVSZXF1ZXN0GhwucGxhdG8uUGFnaW5hdGVUb3BpY1Jlc3BvbnNlIgASPQoMR2V0VG9waWNCeUlkEhUucGxhdG8uVG9waWNJZFJlcXVlc3QaFC5wbGF0by5Ub3BpY1Jlc3BvbnNlIgASPAoOR2V0VG9waWNCeVNsdWcSEi5wbGF0by5TbHVnUmVxdWVzdBoULnBsYXRvLlRvcGljUmVzcG9uc2UiAEIRWg9wbGF0by9hcGkvcHJvdG9iBnByb3RvMw",
    [file_core_core, file_plato_generic, file_plato_object],
  );

/**
 * @generated from message plato.PaginateTopicResponse
 */
export type PaginateTopicResponse = Message<"plato.PaginateTopicResponse"> & {
  /**
   * @generated from field: plato.BaseResponse base = 1;
   */
  base?: BaseResponse;

  /**
   * @generated from field: repeated plato.Topic topics = 2;
   */
  topics: Topic[];
};

/**
 * Describes the message plato.PaginateTopicResponse.
 * Use `create(PaginateTopicResponseSchema)` to create a new message.
 */
export const PaginateTopicResponseSchema: GenMessage<PaginateTopicResponse> =
  /*@__PURE__*/
  messageDesc(file_plato_topic, 0);

/**
 * @generated from message plato.TopicResponse
 */
export type TopicResponse = Message<"plato.TopicResponse"> & {
  /**
   * @generated from field: plato.BaseResponse base = 1;
   */
  base?: BaseResponse;

  /**
   * @generated from field: plato.Topic topic = 2;
   */
  topic?: Topic;
};

/**
 * Describes the message plato.TopicResponse.
 * Use `create(TopicResponseSchema)` to create a new message.
 */
export const TopicResponseSchema: GenMessage<TopicResponse> =
  /*@__PURE__*/
  messageDesc(file_plato_topic, 1);

/**
 * @generated from message plato.InsertTopicRequest
 */
export type InsertTopicRequest = Message<"plato.InsertTopicRequest"> & {
  /**
   * @generated from field: plato.BaseRequest base = 1;
   */
  base?: BaseRequest;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * @generated from field: string icon_url = 4;
   */
  iconUrl: string;

  /**
   * @generated from field: string banner_url = 5;
   */
  bannerUrl: string;

  /**
   * @generated from field: string slug = 6;
   */
  slug: string;
};

/**
 * Describes the message plato.InsertTopicRequest.
 * Use `create(InsertTopicRequestSchema)` to create a new message.
 */
export const InsertTopicRequestSchema: GenMessage<InsertTopicRequest> =
  /*@__PURE__*/
  messageDesc(file_plato_topic, 2);

/**
 * @generated from message plato.UpdateTopicRequest
 */
export type UpdateTopicRequest = Message<"plato.UpdateTopicRequest"> & {
  /**
   * @generated from field: plato.BaseRequest base = 1;
   */
  base?: BaseRequest;

  /**
   * @generated from field: uint64 id = 2;
   */
  id: bigint;

  /**
   * @generated from field: optional string title = 3;
   */
  title?: string;

  /**
   * @generated from field: optional string description = 4;
   */
  description?: string;

  /**
   * @generated from field: optional string icon_url = 5;
   */
  iconUrl?: string;

  /**
   * @generated from field: optional string banner_url = 6;
   */
  bannerUrl?: string;
};

/**
 * Describes the message plato.UpdateTopicRequest.
 * Use `create(UpdateTopicRequestSchema)` to create a new message.
 */
export const UpdateTopicRequestSchema: GenMessage<UpdateTopicRequest> =
  /*@__PURE__*/
  messageDesc(file_plato_topic, 3);

/**
 * @generated from service plato.PlatoTopicService
 */
export const PlatoTopicService: GenService<{
  /**
   * @generated from rpc plato.PlatoTopicService.InsertTopic
   */
  insertTopic: {
    methodKind: "unary";
    input: typeof InsertTopicRequestSchema;
    output: typeof TopicResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoTopicService.UpdateTopic
   */
  updateTopic: {
    methodKind: "unary";
    input: typeof UpdateTopicRequestSchema;
    output: typeof TopicResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoTopicService.DeleteTopic
   */
  deleteTopic: {
    methodKind: "unary";
    input: typeof TopicIdRequestSchema;
    output: typeof GenericResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoTopicService.PaginateTopic
   */
  paginateTopic: {
    methodKind: "unary";
    input: typeof PaginateRequestSchema;
    output: typeof PaginateTopicResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoTopicService.GetTopicById
   */
  getTopicById: {
    methodKind: "unary";
    input: typeof TopicIdRequestSchema;
    output: typeof TopicResponseSchema;
  };
  /**
   * @generated from rpc plato.PlatoTopicService.GetTopicBySlug
   */
  getTopicBySlug: {
    methodKind: "unary";
    input: typeof SlugRequestSchema;
    output: typeof TopicResponseSchema;
  };
}> = /*@__PURE__*/ serviceDesc(file_plato_topic, 0);
